// ==========================================================
// คลังคำศัพท์ TOPIK 1
// ==========================================================
window.flashVocabData1 = [
{ word:"가게", meaning:"ร้านค้า" },
{ word:"가격", meaning:"ราคา" },
{ word:"가구", meaning:"เฟอร์นิเจอร์" },
{ word:"가깝다", meaning:"ใกล้" },
{ word:"가끔", meaning:"บางครั้ง" },
{ word:"가다", meaning:"ไป" },
{ word:"가르치다", meaning:"สอน" },
{ word:"가방", meaning:"กระเป๋า" },
{ word:"가볍다", meaning:"เบา" },
{ word:"가수", meaning:"นักร้อง" },
{ word:"가슴", meaning:"อก, หน้าอก" },
{ word:"가요", meaning:"เพลง" },
{ word:"가운데", meaning:"ตรงกลาง" },
{ word:"가위", meaning:"กรรไกร" },
{ word:"가을", meaning:"ฤดูใบไม้ร่วง" },
{ word:"가장", meaning:"ที่สุด, มากที่สุด" },
{ word:"가져가다", meaning:"เอาไป" },
{ word:"가져오다", meaning:"เอามา" },
{ word:"가족", meaning:"ครอบครัว" },
{ word:"가지", meaning:"กิ่งไม้" },
{ word:"가지다", meaning:"มี" },
{ word:"각", meaning:"แต่ละ" },
{ word:"간", meaning:"ระหว่าง, ขณะ" },
{ word:"간단하다", meaning:"ง่าย, เรียบง่าย" },
{ word:"간단히", meaning:"อย่างง่ายๆ" },
{ word:"간식", meaning:"ของว่าง" },
{ word:"간장", meaning:"ซอสถั่วเหลือง" },
{ word:"간호사", meaning:"พยาบาล" },
{ word:"갈비", meaning:"ซี่โครง" },
{ word:"갈비탕", meaning:"ซุปซี่โครง" },
{ word:"갈색", meaning:"สีน้ำตาล" },
{ word:"갈아타다", meaning:"เปลี่ยนขบวน, ต่อรถ" },
{ word:"감", meaning:"ลูกพลับ" },
{ word:"감기", meaning:"หวัด" },
{ word:"감기약", meaning:"ยาแก้หวัด" },
{ word:"감다", meaning:"หลับตา" },
{ word:"감동", meaning:"ความประทับใจ" },
{ word:"감동하다", meaning:"ประทับใจ" },
{ word:"감사", meaning:"ขอบคุณ" },
{ word:"감사드립니다", meaning:"ขอบคุณครับ/ค่ะ" },
{ word:"감사하다", meaning:"ขอบคุณ, รู้สึกซาบซึ้ง" },
{ word:"감사합니다", meaning:"ขอบคุณ" },
{ word:"감자", meaning:"มันฝรั่ง" },
{ word:"감자탕", meaning:"ซุปมันฝรั่ง" },
{ word:"갑자기", meaning:"ทันใดนั้น, อย่างกะทันหัน" },
{ word:"값", meaning:"ราคา" },
{ word:"강", meaning:"แม่น้ำ" },
{ word:"강아지", meaning:"ลูกสุนัข" },
{ word:"강좌", meaning:"การบรรยาย, คอร์สเรียน" },
{ word:"갖다", meaning:"มี" },
{ word:"같다", meaning:"เหมือนกัน" },
{ word:"같이", meaning:"ด้วยกัน" },
{ word:"개", meaning:"สุนัข, ชิ้น" },
{ word:"개나리", meaning:"ดอกโฟไซเทีย" },
{ word:"개인", meaning:"บุคคล" },
{ word:"거기", meaning:"ที่นั่น" },
{ word:"거리", meaning:"ถนน" },
{ word:"거실", meaning:"ห้องนั่งเล่น" },
{ word:"거울", meaning:"กระจก" },
{ word:"거의", meaning:"เกือบ, แทบจะ" },
{ word:"거짓말", meaning:"การโกหก" },
{ word:"걱정", meaning:"ความกังวล" },
{ word:"걱정하다", meaning:"กังวล" },
{ word:"건강", meaning:"สุขภาพ" },
{ word:"건강하다", meaning:"มีสุขภาพดี" },
{ word:"건너가다", meaning:"ข้ามไป" },
{ word:"건너다", meaning:"ข้าม" },
{ word:"건너편", meaning:"อีกฝั่งหนึ่ง, ฝั่งตรงข้าม" },
{ word:"건물", meaning:"อาคาร" },
{ word:"건배", meaning:"ชนแก้ว" },
{ word:"걷다", meaning:"เดิน" },
{ word:"걸다", meaning:"แขวน, โทร" },
{ word:"걸리다", meaning:"ใช้เวลา, ติด" },
{ word:"걸어가다", meaning:"เดินไป" },
{ word:"걸어오다", meaning:"เดินมา" },
{ word:"검은색", meaning:"สีดำ" },
{ word:"것", meaning:"สิ่ง, อัน" },
{ word:"게임", meaning:"เกม" },
{ word:"겨울", meaning:"ฤดูหนาว" },
{ word:"겨울방학", meaning:"ปิดเทอมฤดูหนาว" },
{ word:"결과", meaning:"ผลลัพธ์" },
{ word:"결정", meaning:"การตัดสินใจ" },
{ word:"결정하다", meaning:"ตัดสินใจ" },
{ word:"결혼", meaning:"การแต่งงาน" },
{ word:"결혼식", meaning:"งานแต่งงาน" },
{ word:"결혼하다", meaning:"แต่งงาน" },
{ word:"경기", meaning:"การแข่งขัน" },
{ word:"경기장", meaning:"สนามกีฬา" },
{ word:"경복궁", meaning:"พระราชวังคยองบกกุง" },
{ word:"경주", meaning:"เมืองคย็องจู" },
{ word:"경찰", meaning:"ตำรวจ" },
{ word:"경찰관", meaning:"เจ้าหน้าที่ตำรวจ" },
{ word:"경찰서", meaning:"สถานีตำรวจ" },
{ word:"경치", meaning:"ทิวทัศน์, วิวสวยงาม" },
{ word:"경험", meaning:"ประสบการณ์" },
{ word:"계단", meaning:"บันได" },
{ word:"계란", meaning:"ไข่" },
{ word:"계산하다", meaning:"คำนวณ, จ่ายเงิน" },
{ word:"계속", meaning:"ต่อเนื่อง" },
{ word:"계시다", meaning:"อยู่ (รูปสุภาพ)" },
{ word:"계절", meaning:"ฤดูกาล" },
{ word:"계획", meaning:"แผน" },
{ word:"고기", meaning:"เนื้อสัตว์" },
{ word:"고등학교", meaning:"โรงเรียนมัธยมปลาย" },
{ word:"고등학생", meaning:"นักเรียนมัธยมปลาย" },
{ word:"고르다", meaning:"เลือก" },
{ word:"고마웠습니다", meaning:"ขอบคุณ (อดีต)" },
{ word:"고맙다", meaning:"ขอบคุณ" },
{ word:"고맙습니다", meaning:"ขอบคุณ" },
{ word:"고모", meaning:"อาสาว (พี่สาว/น้องสาวของพ่อ)" },
{ word:"고모부", meaning:"อาเขย (สามีของพี่สาว/น้องสาวพ่อ)" },
{ word:"고속버스", meaning:"รถบัสด่วน" },
{ word:"고양이", meaning:"แมว" },
{ word:"고장", meaning:"เสีย, ขัดข้อง" },
{ word:"고추", meaning:"พริก" },
{ word:"고추장", meaning:"โคชูจัง, พริกแดงหมัก" },
{ word:"고치다", meaning:"ซ่อม" },
{ word:"고프다", meaning:"หิว" },
{ word:"고향", meaning:"บ้านเกิด" },
{ word:"곧", meaning:"เร็วๆ นี้" },
{ word:"골목", meaning:"ซอย, ตรอก" },
{ word:"골프", meaning:"กอล์ฟ" },
{ word:"곱다", meaning:"สวยงาม" },
{ word:"곳", meaning:"สถานที่" },
{ word:"공", meaning:"ลูกบอล" },
{ word:"공간", meaning:"พื้นที่" },
{ word:"공기", meaning:"อากาศ" },
{ word:"공무원", meaning:"ข้าราชการ" },
{ word:"공부", meaning:"การเรียน" },
{ word:"공부하다", meaning:"เรียน" },
{ word:"공연", meaning:"การแสดง" },
{ word:"공원", meaning:"สวนสาธารณะ" },
{ word:"공중전화", meaning:"โทรศัพท์สาธารณะ" },
{ word:"공짜", meaning:"ฟรี" },
{ word:"공책", meaning:"สมุดโน้ต" },
{ word:"공항", meaning:"สนามบิน" },
{ word:"공휴일", meaning:"วันหยุดราชการ" },
{ word:"과", meaning:"ฝ่าย, แผนก" },
{ word:"과거", meaning:"อดีต" },
{ word:"과일", meaning:"ผลไม้" },
{ word:"과자", meaning:"ขนม" },
{ word:"과학", meaning:"วิทยาศาสตร์" },
{ word:"관계", meaning:"ความสัมพันธ์" },
{ word:"관광하다", meaning:"ท่องเที่ยว" },
{ word:"관심", meaning:"ความสนใจ" },
{ word:"광고", meaning:"โฆษณา" },
{ word:"괜찮다", meaning:"โอเค, ไม่เป็นไร" },
{ word:"괜찮습니다", meaning:"ไม่เป็นไร" },
{ word:"교과서", meaning:"หนังสือเรียน" },
{ word:"교수", meaning:"อาจารย์มหาวิทยาลัย" },
{ word:"교실", meaning:"ห้องเรียน" },
{ word:"교체", meaning:"การเปลี่ยน, การสับเปลี่ยน" },
{ word:"교통", meaning:"การจราจร" },
{ word:"교통사고", meaning:"อุบัติเหตุทางรถยนต์" },
{ word:"교회", meaning:"โบสถ์" },
{ word:"구", meaning:"เก้า (9)" },
{ word:"구경하다", meaning:"ดู, ชม" },
{ word:"구두", meaning:"รองเท้าหนัง" },
{ word:"구름", meaning:"เมฆ" },
{ word:"구십", meaning:"เก้าสิบ (90)" },
{ word:"구월", meaning:"เดือนกันยายน" },
{ word:"구하다", meaning:"หา, ช่วย" },
{ word:"국", meaning:"ซุป" },
{ word:"국내", meaning:"ในประเทศ" },
{ word:"국립", meaning:"แห่งชาติ, ของรัฐ" },
{ word:"국수", meaning:"เส้นก๋วยเตี๋ยว" },
{ word:"국어", meaning:"ภาษาเกาหลี" },
{ word:"국적", meaning:"สัญชาติ" },
{ word:"국제", meaning:"นานาชาติ" },
{ word:"군인", meaning:"ทหาร" },
{ word:"굽다", meaning:"อบ, ย่าง" },
{ word:"권", meaning:"เล่ม (หนังสือ)" },
{ word:"귀", meaning:"หู" },
{ word:"귀엽다", meaning:"น่ารัก" },
{ word:"규칙", meaning:"กฎ, ระเบียบ" },
{ word:"귤", meaning:"ส้มแมนดาริน" },
{ word:"그", meaning:"นั้น, เขา" },
{ word:"그거", meaning:"อันนั้น" },
{ word:"그것", meaning:"อันนั้น" },
{ word:"그곳", meaning:"ที่นั่น" },
{ word:"그날", meaning:"วันนั้น" },
{ word:"그냥", meaning:"อย่างนั้น, เฉยๆ" },
{ word:"그동안", meaning:"ในระหว่างนั้น, ตลอดช่วงเวลานั้น" },
{ word:"그들", meaning:"พวกเขา" },
{ word:"그때", meaning:"ตอนนั้น" },
{ word:"그래", meaning:"ใช่, โอเค" },
{ word:"그래서", meaning:"ดังนั้น" },
{ word:"그램", meaning:"กรัม" },
{ word:"그러나", meaning:"แต่, อย่างไรก็ตาม" },
{ word:"그러니까", meaning:"ดังนั้น, เพราะฉะนั้น" },
{ word:"그러면", meaning:"ถ้าอย่างนั้น" },
{ word:"그런", meaning:"แบบนั้น" },
{ word:"그런데", meaning:"แต่, อย่างไรก็ตาม" },
{ word:"그럼", meaning:"ถ้าอย่างนั้น" },
{ word:"그렇게", meaning:"อย่างนั้น" },
{ word:"그렇구나", meaning:"อ้อ, เข้าใจแล้ว" },
{ word:"그렇다", meaning:"ใช่, เป็นอย่างนั้น" },
{ word:"그렇습니다", meaning:"ใช่แล้วครับ/ค่ะ" },
{ word:"그렇지만", meaning:"อย่างไรก็ตาม, แต่" },
{ word:"그릇", meaning:"ชาม, ภาชนะ" },
{ word:"그리고", meaning:"และ" },
{ word:"그리다", meaning:"วาด" },
{ word:"그림", meaning:"ภาพวาด, รูป" },
{ word:"그만", meaning:"หยุด, พอแค่นั้น" },
{ word:"그분", meaning:"ท่านนั้น, คนนั้น" },
{ word:"그저께", meaning:"วันก่อนเมื่อวาน" },
{ word:"그중", meaning:"ในบรรดานั้น" },
{ word:"그쪽", meaning:"ที่นั่น, คนนั้น" },
{ word:"그치다", meaning:"หยุด, สิ้นสุด" },
{ word:"극장", meaning:"โรงละคร, โรงหนัง" },
{ word:"근처", meaning:"บริเวณใกล้เคียง" },
{ word:"글", meaning:"ข้อความ, ตัวอักษร" },
{ word:"글쎄요", meaning:"ไม่แน่ใจ, อืม" },
{ word:"금방", meaning:"เดี๋ยวนี้, เมื่อกี้" },
{ word:"금연", meaning:"ห้ามสูบบุหรี่" },
{ word:"금요일", meaning:"วันศุกร์" },
{ word:"금주", meaning:"งดเครื่องดื่มแอลกอฮอล์" },
{ word:"급", meaning:"ระดับ, ชั้น" },
{ word:"급하다", meaning:"รีบ, เร่งด่วน" },
{ word:"기간", meaning:"ระยะเวลา, ช่วงเวลา" },
{ word:"기다리다", meaning:"รอ" },
{ word:"기르다", meaning:"เลี้ยง, ปลูก" },
{ word:"기름", meaning:"น้ำมัน" },
{ word:"기분", meaning:"ความรู้สึก, อารมณ์" },
{ word:"기뻐하다", meaning:"ดีใจ, ยินดี" },
{ word:"기쁘다", meaning:"มีความสุข, ดีใจ" },
{ word:"기사", meaning:"บทความ, คนขับ, ช่าง" },
{ word:"기숙사", meaning:"หอพัก" },
{ word:"기억하다", meaning:"จำได้" },
{ word:"기온", meaning:"อุณหภูมิ" },
{ word:"기자", meaning:"นักข่าว" },
{ word:"기차", meaning:"รถไฟ" },
{ word:"기침", meaning:"ไอ" },
{ word:"기타", meaning:"อื่นๆ" },
{ word:"긴장되다", meaning:"ตื่นเต้น, เครียด" },
{ word:"길", meaning:"ถนน, ทาง" },
{ word:"길다", meaning:"ยาว" },
{ word:"김", meaning:"สาหร่าย" },
{ word:"김밥", meaning:"คิมบับ" },
{ word:"김치", meaning:"กิมจิ" },
{ word:"김치찌개", meaning:"ซุปกิมจิ" },
{ word:"김포공항", meaning:"สนามบินกิมโป" },
{ word:"까만색", meaning:"สีดำ" },
{ word:"까맣다", meaning:"ดำ" },
{ word:"깎다", meaning:"ตัด, โกน" },
{ word:"깜짝", meaning:"ตกใจ, แปลกใจ" },
{ word:"깨끗하다", meaning:"สะอาด" },
{ word:"깨다", meaning:"ตื่น, แตก, ทำแตก" },
{ word:"깨지다", meaning:"แตก, ร้าว" },
{ word:"꺼내다", meaning:"หยิบออกมา" },
{ word:"껌", meaning:"หมากฝรั่ง" },
{ word:"꼭", meaning:"อย่างแน่นอน, ต้อง" },
{ word:"꽃", meaning:"ดอกไม้" },
{ word:"꽃집", meaning:"ร้านดอกไม้" },
{ word:"꾸다", meaning:"ฝัน" },
{ word:"꿈", meaning:"ความฝัน" },
{ word:"끄다", meaning:"ปิด (ไฟ/เครื่อง)" },
{ word:"끓이다", meaning:"ต้ม" },
{ word:"끝", meaning:"จุดสิ้นสุด, ปลาย" },
{ word:"끝나다", meaning:"จบ, สิ้นสุด" },
{ word:"끝내다", meaning:"ทำให้เสร็จ" },
{ word:"끼다", meaning:"สวม, เสียบ, (หมอก) ลง" },
{ word:"나", meaning:"ฉัน" },
{ word:"나가다", meaning:"ออกไป" },
{ word:"나누다", meaning:"แบ่ง, แชร์" },
{ word:"나다", meaning:"เกิดขึ้น, ออกมา" },
{ word:"나라", meaning:"ประเทศ" },
{ word:"나무", meaning:"ต้นไม้" },
{ word:"나빠지다", meaning:"แย่ลง, เสื่อมโทรม" },
{ word:"나쁘다", meaning:"แย่, ไม่ดี" },
{ word:"나오다", meaning:"ออกมา, ปรากฏ" },
{ word:"나이", meaning:"อายุ" },
{ word:"나중", meaning:"ทีหลัง, ภายหลัง" },
{ word:"나타나다", meaning:"ปรากฏ" },
{ word:"나흘", meaning:"สี่วัน" },
{ word:"낚시", meaning:"การตกปลา" },
{ word:"날", meaning:"วัน" },
{ word:"날씨", meaning:"อากาศ" },
{ word:"날짜", meaning:"วันที่" },
{ word:"남", meaning:"ทิศใต้, ผู้ชาย" },
{ word:"남기다", meaning:"ทิ้งไว้, เหลือไว้" },
{ word:"남녀", meaning:"ชายและหญิง" },
{ word:"남대문시장", meaning:"ตลาดนัมแดมุน" },
{ word:"남동생", meaning:"น้องชาย" },
{ word:"남미", meaning:"อเมริกาใต้" },
{ word:"남북", meaning:"เหนือและใต้" },
{ word:"남자", meaning:"ผู้ชาย" },
{ word:"남쪽", meaning:"ทิศใต้" },
{ word:"남편", meaning:"สามี" },
{ word:"남학생", meaning:"นักเรียนชาย" },
{ word:"낮", meaning:"กลางวัน" },
{ word:"낮다", meaning:"ต่ำ" },
{ word:"내", meaning:"ของฉัน" },
{ word:"내가", meaning:"ฉัน (ประธาน)" },
{ word:"내과", meaning:"อายุรกรรม" },
{ word:"내년", meaning:"ปีหน้า" },
{ word:"내다", meaning:"จ่าย, ออก" },
{ word:"내려가다", meaning:"ลงไป" },
{ word:"내려오다", meaning:"ลงมา" },
{ word:"내리다", meaning:"ลง" },
{ word:"내용", meaning:"เนื้อหา" },
{ word:"내일", meaning:"พรุ่งนี้" },
{ word:"냄비", meaning:"หม้อ" },
{ word:"냄새", meaning:"กลิ่น" },
{ word:"냉면", meaning:"บะหมี่เย็น" },
{ word:"냉장고", meaning:"ตู้เย็น" },
{ word:"너", meaning:"คุณ, เธอ" },
{ word:"너무", meaning:"เกินไป, มาก" },
{ word:"넓다", meaning:"กว้าง" },
{ word:"넘다", meaning:"เกิน, มากกว่า" },
{ word:"넘어지다", meaning:"ล้ม" },
{ word:"넣다", meaning:"ใส่" },
{ word:"네", meaning:"ใช่, สี่ (4)" },
{ word:"넥타이", meaning:"เนคไท" },
{ word:"넷", meaning:"สี่ (4)" },
{ word:"넷째", meaning:"ที่สี่" },
{ word:"년", meaning:"ปี" },
{ word:"노란색", meaning:"สีเหลือง" },
{ word:"노랗다", meaning:"เหลือง" },
{ word:"노래", meaning:"เพลง" },
{ word:"노래방", meaning:"คาราโอเกะ" },
{ word:"노래하다", meaning:"ร้องเพลง" },
{ word:"노력하다", meaning:"พยายาม, มุ่งมั่น" },
{ word:"노트", meaning:"โน้ต, สมุด" },
{ word:"녹색", meaning:"สีเขียว" },
{ word:"녹차", meaning:"ชาเขียว" },
{ word:"놀다", meaning:"เล่น" },
{ word:"놀라다", meaning:"ประหลาดใจ" },
{ word:"농구", meaning:"บาสเกตบอล" },
{ word:"높다", meaning:"สูง" },
{ word:"놓다", meaning:"วาง" },
{ word:"누가", meaning:"ใคร (ประธาน)" },
{ word:"누구", meaning:"ใคร" },
{ word:"누나", meaning:"พี่สาว (เรียกโดยน้องชาย)" },
{ word:"누르다", meaning:"กด" },
{ word:"눈", meaning:"ตา, หิมะ" },
{ word:"눈물", meaning:"น้ำตา" },
{ word:"눈사람", meaning:"ตุ๊กตาหิมะ" },
{ word:"눈싸움", meaning:"สงครามก้อนหิมะ" },
{ word:"눕다", meaning:"นอน" },
{ word:"뉴스", meaning:"ข่าว" },
{ word:"뉴욕", meaning:"นิวยอร์ก" },
{ word:"느끼다", meaning:"รู้สึก" },
{ word:"느낌", meaning:"ความรู้สึก" },
{ word:"느리다", meaning:"ช้า" },
{ word:"늘", meaning:"เสมอ, ตลอดเวลา" },
{ word:"늘다", meaning:"เพิ่มขึ้น" },
{ word:"능력", meaning:"ความสามารถ" },
{ word:"늦다", meaning:"สาย, ช้า" },
{ word:"늦잠", meaning:"นอนตื่นสาย" },
{ word:"님", meaning:"คุณ (คำเรียกสุภาพ)" },
{ word:"다", meaning:"ทั้งหมด" },
{ word:"다녀오다", meaning:"กลับมา" },
{ word:"다니다", meaning:"ไป-มา, ผ่านไปมา" },
{ word:"다르다", meaning:"ต่างกัน" },
{ word:"다른", meaning:"อื่น, ต่าง" },
{ word:"다리", meaning:"สะพาน, ขา" },
{ word:"다섯", meaning:"ห้า (5)" },
{ word:"다시", meaning:"อีกครั้ง" },
{ word:"다음", meaning:"ถัดไป, ต่อไป" },
{ word:"다음달", meaning:"เดือนหน้า" },
{ word:"다음주", meaning:"สัปดาห์หน้า" },
{ word:"다음해", meaning:"ปีหน้า" },
{ word:"다이어트", meaning:"ไดเอท, ลดน้ำหนัก" },
{ word:"다치다", meaning:"บาดเจ็บ" },
{ word:"닦다", meaning:"เช็ด, ขัด" },
{ word:"단어", meaning:"คำศัพท์" },
{ word:"단점", meaning:"ข้อเสีย" },
{ word:"닫다", meaning:"ปิด" },
{ word:"닫히다", meaning:"ถูกปิด" },
{ word:"달", meaning:"เดือน, พระจันทร์" },
{ word:"달걀", meaning:"ไข่" },
{ word:"달다", meaning:"หวาน" },
{ word:"달러", meaning:"ดอลลาร์" },
{ word:"달력", meaning:"ปฏิทิน" },
{ word:"달리다", meaning:"วิ่ง" },
{ word:"닭", meaning:"ไก่" },
{ word:"닭고기", meaning:"เนื้อไก่" },
{ word:"닮다", meaning:"คล้าย, เหมือน" },
{ word:"담그다", meaning:"แช่, ดอง" },
{ word:"담배", meaning:"บุหรี่" },
{ word:"답장", meaning:"การตอบกลับ" },
{ word:"당근", meaning:"แครอท" },
{ word:"당신", meaning:"คุณ" },
{ word:"대", meaning:"ใหญ่, เทียบกับ" },
{ word:"대답", meaning:"คำตอบ" },
{ word:"대답하다", meaning:"ตอบ" },
{ word:"대부분", meaning:"ส่วนใหญ่" },
{ word:"대사관", meaning:"สถานทูต" },
{ word:"대학", meaning:"มหาวิทยาลัย" },
{ word:"대학교", meaning:"มหาวิทยาลัย" },
{ word:"대학생", meaning:"นักศึกษามหาวิทยาลัย" },
{ word:"대학원", meaning:"บัณฑิตวิทยาลัย" },
{ word:"대학원생", meaning:"นักศึกษาบัณฑิต" },
{ word:"대한민국", meaning:"สาธารณรัฐเกาหลี, เกาหลีใต้" },
{ word:"대화", meaning:"การสนทนา" },
{ word:"대회", meaning:"การแข่งขัน, การประชุม" },
{ word:"댁", meaning:"บ้าน (รูปสุภาพ)" },
{ word:"더", meaning:"มากกว่า, อีก" },
{ word:"더럽다", meaning:"สกปรก" },
{ word:"더운물", meaning:"น้ำร้อน" },
{ word:"덕분", meaning:"เพราะ, ขอบคุณที่" },
{ word:"덥다", meaning:"ร้อน" },
{ word:"덮다", meaning:"คลุม, ปิด" },
{ word:"데리다", meaning:"พาไป, พามา" },
{ word:"데이트", meaning:"เดท, นัดพบ" },
{ word:"도로", meaning:"ถนน" },
{ word:"도서관", meaning:"ห้องสมุด" },
{ word:"도시", meaning:"เมือง" },
{ word:"도와주다", meaning:"ช่วยเหลือ" },
{ word:"도움", meaning:"ความช่วยเหลือ" },
{ word:"도착", meaning:"การมาถึง" },
{ word:"도착하다", meaning:"มาถึง" },
{ word:"도쿄", meaning:"โตเกียว" },
{ word:"독서", meaning:"การอ่านหนังสือ" },
{ word:"독서실", meaning:"ห้องอ่านหนังสือ" },
{ word:"독서하다", meaning:"อ่านหนังสือ" },
{ word:"독일", meaning:"เยอรมนี" },
{ word:"돈", meaning:"เงิน" },
{ word:"돌아가다", meaning:"กลับไป" },
{ word:"돌아오다", meaning:"กลับมา" },
{ word:"돕다", meaning:"ช่วย" },
{ word:"동네", meaning:"ย่าน, ละแวกบ้าน" },
{ word:"동대문시장", meaning:"ตลาดทงแดมุน" },
{ word:"동물", meaning:"สัตว์" },
{ word:"동생", meaning:"น้อง" },
{ word:"동아리", meaning:"ชมรม, กลุ่ม" },
{ word:"동안", meaning:"ระหว่าง, ช่วงเวลา" },
{ word:"동양", meaning:"ตะวันออก, โอเรียนทัล" },
{ word:"동전", meaning:"เหรียญ" },
{ word:"동쪽", meaning:"ทิศตะวันออก" },
{ word:"돼지", meaning:"หมู" },
{ word:"돼지고기", meaning:"เนื้อหมู" },
{ word:"되다", meaning:"กลายเป็น" },
{ word:"된장", meaning:"เต้าเจี้ยวหมัก" },
{ word:"된장국", meaning:"ซุปเต้าเจี้ยว" },
{ word:"된장찌개", meaning:"ซุปเต้าเจี้ยวข้น" },
{ word:"두", meaning:"สอง (2)" },
{ word:"두껍다", meaning:"หนา" },
{ word:"두다", meaning:"วาง" },
{ word:"두부", meaning:"เต้าหู้" },
{ word:"두부찌개", meaning:"ซุปเต้าหู้" },
{ word:"둘", meaning:"สอง (2)" },
{ word:"둘째", meaning:"ที่สอง" },
{ word:"뒤", meaning:"ข้างหลัง, ด้านหลัง" },
{ word:"뒤쪽", meaning:"ด้านหลัง" },
{ word:"드라마", meaning:"ละคร" },
{ word:"드리다", meaning:"ให้ (รูปสุภาพ)" },
{ word:"드시다", meaning:"รับประทาน (รูปสุภาพ)" },
{ word:"듣기", meaning:"การฟัง" },
{ word:"듣다", meaning:"ฟัง" },
{ word:"들", meaning:"ทุ่ง, พหูพจน์" },
{ word:"들다", meaning:"ถือ, เข้า" },
{ word:"들어가다", meaning:"เข้าไป" },
{ word:"들어오다", meaning:"เข้ามา" },
{ word:"등", meaning:"หลัง, และอื่นๆ" },
{ word:"등산", meaning:"การปีนเขา, การเดินป่า" },
{ word:"등산복", meaning:"ชุดปีนเขา" },
{ word:"등산화", meaning:"รองเท้าปีนเขา" },
{ word:"디브이디", meaning:"ดีวีดี" },
{ word:"디자인", meaning:"การออกแบบ" },
{ word:"따뜻하다", meaning:"อบอุ่น" },
{ word:"따라가다", meaning:"ตามไป" },
{ word:"따라오다", meaning:"ตามมา" },
{ word:"따로", meaning:"แยกกัน" },
{ word:"따르다", meaning:"ตาม, ปฏิบัติตาม" },
{ word:"딸", meaning:"ลูกสาว" },
{ word:"딸기", meaning:"สตรอว์เบอร์รี" },
{ word:"땀", meaning:"เหงื่อ" },
{ word:"때", meaning:"เวลา, ตอน" },
{ word:"때문", meaning:"เพราะ" },
{ word:"떠나다", meaning:"ออกจาก, จากไป" },
{ word:"떠들다", meaning:"พูดเสียงดัง, อึกทึก" },
{ word:"떡", meaning:"ต็อก, ขนมข้าว" },
{ word:"떡국", meaning:"ซุปต็อก" },
{ word:"떡볶이", meaning:"ต็อกโบกี" },
{ word:"떨어지다", meaning:"ตก, หล่น" },
{ word:"또", meaning:"อีก, นอกจากนี้" },
{ word:"또는", meaning:"หรือ" },
{ word:"똑같다", meaning:"เหมือนกันทุกอย่าง" },
{ word:"똑바로", meaning:"ตรงๆ, ตั้งตรง" },
{ word:"뛰다", meaning:"วิ่ง" },
{ word:"뜨겁다", meaning:"ร้อนมาก" },
{ word:"뜨다", meaning:"ขึ้น, ลืมตา" },
{ word:"뜻", meaning:"ความหมาย" },
{ word:"라디오", meaning:"วิทยุ" },
{ word:"라면", meaning:"ราเมง" },
{ word:"러시아", meaning:"รัสเซีย" },
{ word:"로션", meaning:"โลชั่น" },
{ word:"마늘", meaning:"กระเทียม" },
{ word:"마르다", meaning:"แห้ง" },
{ word:"마리", meaning:"ตัว (นับสัตว์)" },
{ word:"마시다", meaning:"ดื่ม" },
{ word:"마음", meaning:"ใจ, ความรู้สึก" },
{ word:"마지막", meaning:"สุดท้าย" },
{ word:"마치다", meaning:"เสร็จสิ้น, จบ" },
{ word:"마흔", meaning:"สี่สิบ (40)" },
{ word:"막히다", meaning:"ติดขัด, อุดตัน" },
{ word:"만", meaning:"เพียง, หมื่น" },
{ word:"만나다", meaning:"พบ, เจอ" },
{ word:"만두", meaning:"เกี๊ยว" },
{ word:"만들다", meaning:"ทำ, สร้าง" },
{ word:"만일", meaning:"ถ้า, หาก" },
{ word:"만지다", meaning:"สัมผัส, จับ" },
{ word:"만화", meaning:"การ์ตูน" },
{ word:"많다", meaning:"มาก" },
{ word:"많이", meaning:"มาก" },
{ word:"말", meaning:"คำ, การพูด" },
{ word:"말씀", meaning:"คำพูด (รูปสุภาพ)" },
{ word:"말씀하다", meaning:"พูด (รูปสุภาพ)" },
{ word:"말하기", meaning:"การพูด" },
{ word:"말하다", meaning:"พูด, บอก" },
{ word:"맑다", meaning:"맑다, สดใส" },
{ word:"맛", meaning:"รสชาติ" },
{ word:"맛없다", meaning:"ไม่อร่อย" },
{ word:"맛있다", meaning:"อร่อย" },
{ word:"맞다", meaning:"ถูกต้อง, พอดี" },
{ word:"맞습니다", meaning:"ถูกต้องครับ/ค่ะ" },
{ word:"맞아요", meaning:"ถูกต้องค่ะ/ครับ" },
{ word:"맞은편", meaning:"ฝั่งตรงข้าม" },
{ word:"매다", meaning:"ผูก" },
{ word:"매우", meaning:"มาก, อย่างยิ่ง" },
{ word:"매일", meaning:"ทุกวัน" },
{ word:"매주", meaning:"ทุกสัปดาห์" },
{ word:"맥주", meaning:"เบียร์" },
{ word:"맵다", meaning:"เผ็ด" },
{ word:"머리", meaning:"หัว, ผม" },
{ word:"먹다", meaning:"กิน" },
{ word:"먼저", meaning:"ก่อน, เป็นคนแรก" },
{ word:"멀다", meaning:"ไกล" },
{ word:"멋있다", meaning:"เท่, ดูดี" },
{ word:"메뉴", meaning:"เมนู" },
{ word:"메다", meaning:"แบกบนไหล่" },
{ word:"메모", meaning:"บันทึก" },
{ word:"메시지", meaning:"ข้อความ" },
{ word:"멕시코", meaning:"เม็กซิโก" },
{ word:"며칠", meaning:"กี่วัน, วันที่เท่าไร" },
{ word:"면도", meaning:"การโกนหนวด" },
{ word:"명", meaning:"คน (ลักษณนาม)" },
{ word:"명절", meaning:"วันหยุดประเพณี" },
{ word:"몇", meaning:"กี่, จำนวนหนึ่ง" },
{ word:"모두", meaning:"ทั้งหมด, ทุกคน" },
{ word:"모레", meaning:"มะรืนนี้" },
{ word:"모르겠습니다", meaning:"ไม่ทราบครับ/ค่ะ" },
{ word:"모르다", meaning:"ไม่รู้" },
{ word:"모시다", meaning:"พาไป, รับใช้ (รูปสุภาพ)" },
{ word:"모양", meaning:"รูปร่าง, แบบ" },
{ word:"모으다", meaning:"เก็บ, รวบรวม" },
{ word:"모이다", meaning:"รวมตัว, มารวมกัน" },
{ word:"모임", meaning:"การประชุม, การรวมตัว" },
{ word:"모자", meaning:"หมวก" },
{ word:"목", meaning:"คอ, ลำคอ" },
{ word:"목걸이", meaning:"สร้อยคอ" },
{ word:"목소리", meaning:"เสียง" },
{ word:"목요일", meaning:"วันพฤหัสบดี" },
{ word:"목욕", meaning:"การอาบน้ำ" },
{ word:"목욕하다", meaning:"อาบน้ำ" },
{ word:"목적", meaning:"จุดประสงค์" },
{ word:"몸", meaning:"ร่างกาย" },
{ word:"몸살", meaning:"ป่วยเพราะความล้า" },
{ word:"못하다", meaning:"ทำไม่ได้" },
{ word:"몽골", meaning:"มองโกเลีย" },
{ word:"무", meaning:"หัวไชเท้า" },
{ word:"무겁다", meaning:"หนัก" },
{ word:"무궁화", meaning:"ดอกชบาเกาหลี" },
{ word:"무료", meaning:"ฟรี" },
{ word:"무릎", meaning:"เข่า" },
{ word:"무리", meaning:"กลุ่ม, เกินไป" },
{ word:"무섭다", meaning:"น่ากลัว" },
{ word:"무슨", meaning:"อะไร, ชนิดไหน" },
{ word:"무엇", meaning:"อะไร" },
{ word:"무엇이", meaning:"อะไร (ประธาน)" },
{ word:"무역", meaning:"การค้า" },
{ word:"무용", meaning:"การเต้นรำ" },
{ word:"무척", meaning:"มาก, อย่างยิ่ง" },
{ word:"문", meaning:"ประตู" },
{ word:"문구점", meaning:"ร้านเครื่องเขียน" },
{ word:"문장", meaning:"ประโยค" },
{ word:"문제", meaning:"ปัญหา" },
{ word:"문화", meaning:"วัฒนธรรม" },
{ word:"묻다", meaning:"ถาม" },
{ word:"물", meaning:"น้ำ" },
{ word:"물건", meaning:"ของ, สิ่งของ" },
{ word:"물론", meaning:"แน่นอน" },
{ word:"물어보다", meaning:"ถาม" },
{ word:"뭐", meaning:"อะไร" },
{ word:"미국", meaning:"สหรัฐอเมริกา" },
{ word:"미래", meaning:"อนาคต" },
{ word:"미리", meaning:"ล่วงหน้า" },
{ word:"미술", meaning:"ศิลปะ" },
{ word:"미술관", meaning:"หอศิลป์" },
{ word:"미안하다", meaning:"เสียใจ, ขอโทษ" },
{ word:"미안합니다", meaning:"ขอโทษครับ/ค่ะ" },
{ word:"미용실", meaning:"ร้านเสริมสวย" },
{ word:"미터", meaning:"เมตร" },
{ word:"민속촌", meaning:"หมู่บ้านพื้นบ้าน" },
{ word:"밀가루", meaning:"แป้งสาลี" },
{ word:"밀리다", meaning:"ถูกผลัก, ถูกโกน" },
{ word:"밑", meaning:"ด้านล่าง, ใต้" },
{ word:"바꾸다", meaning:"เปลี่ยน" },
{ word:"바뀌다", meaning:"เปลี่ยนไป" },
{ word:"바나나", meaning:"กล้วย" },
{ word:"바다", meaning:"ทะเล" },
{ word:"바닷가", meaning:"ชายหาด" },
{ word:"바라다", meaning:"หวัง" },
{ word:"바람", meaning:"ลม" },
{ word:"바로", meaning:"ทันที, ตรงๆ" },
{ word:"바르다", meaning:"ถูกต้อง, ทา" },
{ word:"바쁘다", meaning:"ยุ่ง" },
{ word:"바이올린", meaning:"ไวโอลิน" },
{ word:"바지", meaning:"กางเกง" },
{ word:"박물관", meaning:"พิพิธภัณฑ์" },
{ word:"박수", meaning:"การปรบมือ" },
{ word:"밖", meaning:"ข้างนอก" },
{ word:"반", meaning:"ครึ่ง, กลุ่ม" },
{ word:"반갑다", meaning:"ยินดีที่ได้พบ" },
{ word:"반갑습니다", meaning:"ยินดีที่ได้รู้จักครับ/ค่ะ" },
{ word:"반년", meaning:"ครึ่งปี" },
{ word:"반달", meaning:"พระจันทร์ครึ่งเสี้ยว" },
{ word:"반바지", meaning:"กางเกงขาสั้น" },
{ word:"반지", meaning:"แหวน" },
{ word:"반찬", meaning:"กับข้าว, เครื่องเคียง" },
{ word:"받다", meaning:"รับ" },
{ word:"발", meaning:"เท้า, ขา" },
{ word:"발가락", meaning:"นิ้วเท้า" },
{ word:"발음", meaning:"การออกเสียง" },
{ word:"발전", meaning:"การพัฒนา" },
{ word:"발표", meaning:"การประกาศ, การนำเสนอ" },
{ word:"밝다", meaning:"สว่าง" },
{ word:"밤", meaning:"กลางคืน" },
{ word:"밥", meaning:"ข้าว, อาหาร" },
{ word:"방", meaning:"ห้อง" },
{ word:"방법", meaning:"วิธีการ" },
{ word:"방송", meaning:"การออกอากาศ" },
{ word:"방송국", meaning:"สถานีวิทยุโทรทัศน์" },
{ word:"방학", meaning:"ปิดเทอม" },
{ word:"배", meaning:"เรือ, ท้อง, ลูกแพร์" },
{ word:"배고프다", meaning:"หิว" },
{ word:"배구", meaning:"วอลเลย์บอล" },
{ word:"배달", meaning:"การส่งของ" },
{ word:"배부르다", meaning:"อิ่ม" },
{ word:"배우", meaning:"นักแสดง" },
{ word:"배우다", meaning:"เรียนรู้" },
{ word:"배탈", meaning:"ปวดท้อง" },
{ word:"백", meaning:"หนึ่งร้อย (100)" },
{ word:"백화점", meaning:"ห้างสรรพสินค้า" },
{ word:"버리다", meaning:"ทิ้ง" },
{ word:"버스", meaning:"รถบัส" },
{ word:"번", meaning:"ครั้ง, เบอร์" },
{ word:"번호", meaning:"หมายเลข" },
{ word:"벌다", meaning:"หาเงิน" },
{ word:"벌써", meaning:"แล้ว, เรียบร้อยแล้ว" },
{ word:"벗다", meaning:"ถอด (เสื้อผ้า, รองเท้า)" },
{ word:"벚꽃", meaning:"ดอกซากุระ" },
{ word:"베이징", meaning:"ปักกิ่ง" },
{ word:"베트남", meaning:"เวียดนาม" },
{ word:"벽", meaning:"กำแพง" },
{ word:"변호사", meaning:"ทนายความ" },
{ word:"별", meaning:"ดาว" },
{ word:"별로", meaning:"ไม่ค่อย" },
{ word:"병", meaning:"โรค, ขวด" },
{ word:"병원", meaning:"โรงพยาบาล" },
{ word:"보내다", meaning:"ส่ง, ใช้เวลา" },
{ word:"보다", meaning:"ดู, เห็น" },
{ word:"보도", meaning:"ทางเท้า, รายงาน" },
{ word:"보이다", meaning:"แสดง, ดูเหมือน" },
{ word:"보통", meaning:"ปกติ, โดยทั่วไป" },
{ word:"복숭아", meaning:"ลูกพีช" },
{ word:"복잡하다", meaning:"ซับซ้อน, แออัด" },
{ word:"볶다", meaning:"ผัด" },
{ word:"볶음밥", meaning:"ข้าวผัด" },
{ word:"볼펜", meaning:"ปากกาลูกลื่น" },
{ word:"봄", meaning:"ฤดูใบไม้ผลิ" },
{ word:"봉지", meaning:"ถุง" },
{ word:"봉투", meaning:"ซอง" },
{ word:"뵙다", meaning:"พบ (รูปสุภาพ)" },
{ word:"부동산", meaning:"อสังหาริมทรัพย์" },
{ word:"부드럽다", meaning:"นุ่ม, อ่อนโยน" },
{ word:"부르다", meaning:"เรียก, ร้องเพลง" },
{ word:"부모", meaning:"พ่อแม่" },
{ word:"부부", meaning:"คู่สมรส" },
{ word:"부산", meaning:"เมืองปูซาน" },
{ word:"부업", meaning:"งานเสริม" },
{ word:"부엌", meaning:"ครัว" },
{ word:"부인", meaning:"ภรรยา, คุณนาย" },
{ word:"부장", meaning:"ผู้อำนวยการ, หัวหน้าแผนก" },
{ word:"부지런하다", meaning:"ขยัน" },
{ word:"부치다", meaning:"ส่ง, ทอด" },
{ word:"부탁", meaning:"คำขอร้อง" },
{ word:"부탁하다", meaning:"ขอร้อง" },
{ word:"북쪽", meaning:"ทิศเหนือ" },
{ word:"분", meaning:"คน (รูปสุภาพ), นาที" },
{ word:"분위기", meaning:"บรรยากาศ" },
{ word:"불", meaning:"ไฟ, แสงไฟ" },
{ word:"불고기", meaning:"บุลโกกิ" },
{ word:"불다", meaning:"เป่า (ลม, เครื่องดนตรี)" },
{ word:"불편하다", meaning:"ไม่สะดวก, อึดอัด" },
{ word:"붓다", meaning:"เท" },
{ word:"붙다", meaning:"ติด, สอบผ่าน" },
{ word:"붙이다", meaning:"ติด, แปะ" },
{ word:"브라질", meaning:"บราซิล" },
{ word:"블라우스", meaning:"เสื้อบลาวส์" },
{ word:"비", meaning:"ฝน" },
{ word:"비누", meaning:"สบู่" },
{ word:"비디오", meaning:"วิดีโอ" },
{ word:"비밀", meaning:"ความลับ" },
{ word:"비빔밥", meaning:"บิบิมบับ" },
{ word:"비슷하다", meaning:"คล้ายกัน" },
{ word:"비싸다", meaning:"แพง" },
{ word:"비행기", meaning:"เครื่องบิน" },
{ word:"비행장", meaning:"สนามบิน" },
{ word:"빌딩", meaning:"ตึก, อาคาร" },
{ word:"빌리다", meaning:"ยืม, ให้ยืม" },
{ word:"빠르다", meaning:"เร็ว" },
{ word:"빨간색", meaning:"สีแดง" },
{ word:"빨갛다", meaning:"แดง" },
{ word:"빨다", meaning:"ดูด, ซัก" },
{ word:"빨래", meaning:"การซักผ้า, ผ้าที่ซัก" },
{ word:"빨리", meaning:"เร็วๆ" },
{ word:"빵", meaning:"ขนมปัง" },
{ word:"빵집", meaning:"ร้านขนมปัง" },
{ word:"빼다", meaning:"เอาออก, ดึงออก" },
{ word:"뿐", meaning:"เท่านั้น" },
{ word:"사", meaning:"สี่ (4)" },
{ word:"사거리", meaning:"สี่แยก" },
{ word:"사계절", meaning:"สี่ฤดูกาล" },
{ word:"사고", meaning:"อุบัติเหตุ" },
{ word:"사과", meaning:"แอปเปิล" },
{ word:"사다", meaning:"ซื้อ" },
{ word:"사람", meaning:"คน" },
{ word:"사랑", meaning:"ความรัก" },
{ word:"사랑하다", meaning:"รัก" },
{ word:"사례", meaning:"กรณี, ตัวอย่าง" },
{ word:"사무실", meaning:"สำนักงาน" },
{ word:"사물", meaning:"วัตถุ, สิ่งของ" },
{ word:"사십", meaning:"สี่สิบ (40)" },
{ word:"사업가", meaning:"นักธุรกิจ" },
{ word:"사용하다", meaning:"ใช้" },
{ word:"사원", meaning:"วัด, พนักงาน" },
{ word:"사월", meaning:"เดือนเมษายน" },
{ word:"사이", meaning:"ระหว่าง" },
{ word:"사이다", meaning:"น้ำอัดลมใส" },
{ word:"사이즈", meaning:"ขนาด" },
{ word:"사인하다", meaning:"เซ็นชื่อ" },
{ word:"사장", meaning:"ประธานบริษัท, เจ้านาย" },
{ word:"사전", meaning:"พจนานุกรม" },
{ word:"사진", meaning:"ภาพถ่าย, รูปภาพ" },
{ word:"사진기", meaning:"กล้องถ่ายรูป" },
{ word:"사촌", meaning:"ลูกพี่ลูกน้อง" },
{ word:"사탕", meaning:"ลูกอม" },
{ word:"사흘", meaning:"สามวัน" },
{ word:"산", meaning:"ภูเขา" },
{ word:"산책", meaning:"การเดินเล่น" },
{ word:"살", meaning:"เนื้อ, อายุ (ปี)" },
{ word:"살다", meaning:"อาศัยอยู่, มีชีวิต" },
{ word:"삼", meaning:"สาม (3)" },
{ word:"삼거리", meaning:"สามแยก" },
{ word:"삼계탕", meaning:"ซุปไก่โสม" },
{ word:"삼십", meaning:"สามสิบ (30)" },
{ word:"삼월", meaning:"เดือนมีนาคม" },
{ word:"삼촌", meaning:"ลุง (น้องชายของพ่อ)" },
{ word:"상관", meaning:"ความสัมพันธ์" },
{ word:"상자", meaning:"กล่อง" },
{ word:"상처", meaning:"บาดแผล" },
{ word:"상품", meaning:"สินค้า" },
{ word:"새", meaning:"นก, ใหม่" },
{ word:"새로", meaning:"ใหม่" },
{ word:"새벽", meaning:"รุ่งเช้า, ดึกมาก" },
{ word:"새우", meaning:"กุ้ง" },
{ word:"색", meaning:"สี" },
{ word:"색깔", meaning:"สี" },
{ word:"샌드위치", meaning:"แซนด์วิช" },
{ word:"생각", meaning:"ความคิด" },
{ word:"생각되다", meaning:"ดูเหมือนว่า, ถือว่า" },
{ word:"생각하다", meaning:"คิด" },
{ word:"생기다", meaning:"เกิดขึ้น, มีรูปร่าง" },
{ word:"생선", meaning:"ปลา" },
{ word:"생신", meaning:"วันเกิด (รูปสุภาพ)" },
{ word:"생일", meaning:"วันเกิด" },
{ word:"생활", meaning:"ชีวิต, การดำเนินชีวิต" },
{ word:"샤워하다", meaning:"อาบน้ำฝักบัว" },
{ word:"샴푸", meaning:"แชมพู" },
{ word:"서다", meaning:"ยืน" },
{ word:"서로", meaning:"ซึ่งกันและกัน" },
{ word:"서류", meaning:"เอกสาร" },
{ word:"서른", meaning:"สามสิบ (30)" },
{ word:"서비스", meaning:"บริการ" },
{ word:"서양", meaning:"ตะวันตก" },
{ word:"서울", meaning:"โซล" },
{ word:"서울역", meaning:"สถานีโซล" },
{ word:"서점", meaning:"ร้านหนังสือ" },
{ word:"서쪽", meaning:"ทิศตะวันตก" },
{ word:"선물", meaning:"ของขวัญ" },
{ word:"선배", meaning:"รุ่นพี่" },
{ word:"선생님", meaning:"คุณครู, อาจารย์" },
{ word:"선수", meaning:"นักกีฬา" },
{ word:"선택하다", meaning:"เลือก" },
{ word:"선풍기", meaning:"พัดลม" },
{ word:"설거지", meaning:"การล้างจาน" },
{ word:"설날", meaning:"วันปีใหม่จันทรคติ" },
{ word:"설렁탕", meaning:"ซอลลองทัง (ซุปกระดูกวัว)" },
{ word:"설명", meaning:"คำอธิบาย" },
{ word:"설명하다", meaning:"อธิบาย" },
{ word:"설악산", meaning:"ภูเขาซอรัก" },
{ word:"설탕", meaning:"น้ำตาล" },
{ word:"섬", meaning:"เกาะ" },
{ word:"성", meaning:"ปราสาท, นามสกุล" },
{ word:"성격", meaning:"บุคลิกภาพ" },
{ word:"성함", meaning:"ชื่อ" },
{ word:"세계", meaning:"โลก" },
{ word:"세수하다", meaning:"ล้างหน้า" },
{ word:"세우다", meaning:"ตั้ง, วางแผน" },
{ word:"세일하다", meaning:"ลดราคา" },
{ word:"세탁기", meaning:"เครื่องซักผ้า" },
{ word:"세탁소", meaning:"ร้านซักรีด" },
{ word:"센터", meaning:"ศูนย์" },
{ word:"센티미터", meaning:"เซนติเมตร" },
{ word:"셋", meaning:"สาม (3)" },
{ word:"셋째", meaning:"ที่สาม" },
{ word:"소", meaning:"เล็ก, วัว" },
{ word:"소개", meaning:"การแนะนำตัว" },
{ word:"소개하다", meaning:"แนะนำ" },
{ word:"소고기", meaning:"เนื้อวัว" },
{ word:"소금", meaning:"เกลือ" },
{ word:"소리", meaning:"เสียง" },
{ word:"소설", meaning:"นิยาย" },
{ word:"소설가", meaning:"นักเขียนนิยาย" },
{ word:"소식", meaning:"ข่าวสาร" },
{ word:"소파", meaning:"โซฟา" },
{ word:"소포", meaning:"พัสดุ" },
{ word:"소풍", meaning:"遠足, การไปทัศนศึกษา" },
{ word:"소화제", meaning:"ยาช่วยย่อยอาหาร" },
{ word:"속", meaning:"ข้างใน" },
{ word:"손", meaning:"มือ" },
{ word:"손가락", meaning:"นิ้วมือ" },
{ word:"손님", meaning:"ลูกค้า, แขก" },
{ word:"손수건", meaning:"ผ้าเช็ดหน้า" },
{ word:"송이", meaning:"ช่อ, ดอก" },
{ word:"쇼핑", meaning:"การช้อปปิ้ง" },
{ word:"수건", meaning:"ผ้าเช็ดตัว" },
{ word:"수도", meaning:"เมืองหลวง, ระบบประปา" },
{ word:"수돗물", meaning:"น้ำประปา" },
{ word:"수박", meaning:"แตงโม" },
{ word:"수술하다", meaning:"ผ่าตัด" },
{ word:"수업", meaning:"ชั้นเรียน, บทเรียน" },
{ word:"수영", meaning:"การว่ายน้ำ" },
{ word:"수영복", meaning:"ชุดว่ายน้ำ" },
{ word:"수영장", meaning:"สระว่ายน้ำ" },
{ word:"수요일", meaning:"วันพุธ" },
{ word:"수저", meaning:"ตะเกียบและช้อน" },
{ word:"수첩", meaning:"สมุดโน้ต" },
{ word:"수학", meaning:"คณิตศาสตร์" },
{ word:"숙제", meaning:"การบ้าน" },
{ word:"순서", meaning:"ลำดับ, คิว" },
{ word:"숟가락", meaning:"ช้อน" },
{ word:"술", meaning:"เครื่องดื่มแอลกอฮอล์" },
{ word:"쉬다", meaning:"พัก" },
{ word:"쉰", meaning:"ห้าสิบ (50)" },
{ word:"쉽다", meaning:"ง่าย" },
{ word:"슈퍼마켓", meaning:"ซูเปอร์มาร์เก็ต" },
{ word:"스물", meaning:"ยี่สิบ (20)" },
{ word:"스웨터", meaning:"เสื้อกันหนาว" },
{ word:"스케이트", meaning:"สเก็ต" },
{ word:"스키", meaning:"สกี" },
{ word:"스키장", meaning:"ลานสกี" },
{ word:"스타", meaning:"ดารา" },
{ word:"스타킹", meaning:"ถุงน่อง" },
{ word:"스트레스", meaning:"ความเครียด" },
{ word:"스페인어", meaning:"ภาษาสเปน" },
{ word:"스포츠", meaning:"กีฬา" },
{ word:"슬퍼하다", meaning:"เศร้าโศก" },
{ word:"슬프다", meaning:"เศร้า" },
{ word:"습관", meaning:"นิสัย, ความเคยชิน" },
{ word:"시", meaning:"เมือง, เวลา" },
{ word:"시간", meaning:"เวลา" },
{ word:"시간표", meaning:"ตารางเวลา" },
{ word:"시계", meaning:"นาฬิกา" },
{ word:"시골", meaning:"ชนบท" },
{ word:"시끄럽다", meaning:"ดังมาก, อึกทึก" },
{ word:"시내", meaning:"ใจกลางเมือง" },
{ word:"시다", meaning:"เปรี้ยว" },
{ word:"시디", meaning:"ซีดี" },
{ word:"시민", meaning:"พลเมือง" },
{ word:"시설", meaning:"สิ่งอำนวยความสะดวก" },
{ word:"시외", meaning:"ชานเมือง" },
{ word:"시원하다", meaning:"เย็นสบาย, สดชื่น" },
{ word:"시월", meaning:"เดือนตุลาคม" },
{ word:"시작", meaning:"การเริ่มต้น" },
{ word:"시작되다", meaning:"เริ่มต้น" },
{ word:"시작하다", meaning:"เริ่ม, เริ่มต้น" },
{ word:"시장", meaning:"ตลาด" },
{ word:"시청", meaning:"ศาลาว่าการเมือง" },
{ word:"시키다", meaning:"สั่ง, ให้ทำ" },
{ word:"시험", meaning:"การสอบ" },
{ word:"식당", meaning:"ร้านอาหาร, โรงอาหาร" },
{ word:"식사", meaning:"มื้ออาหาร" },
{ word:"식탁", meaning:"โต๊ะอาหาร" },
{ word:"신", meaning:"พระเจ้า, ใหม่" },
{ word:"신다", meaning:"สวมใส่ (รองเท้า)" },
{ word:"신문", meaning:"หนังสือพิมพ์" },
{ word:"신발", meaning:"รองเท้า" },
{ word:"신청서", meaning:"ใบสมัคร" },
{ word:"신청하다", meaning:"สมัคร, ยื่น" },
{ word:"실례", meaning:"การขอโทษ, ขออนุญาต" },
{ word:"실례하다", meaning:"ขอโทษ" },
{ word:"실수", meaning:"ความผิดพลาด" },
{ word:"싫다", meaning:"ไม่ชอบ, เกลียด" },
{ word:"싫어하다", meaning:"ไม่ชอบ, เกลียด" },
{ word:"심하다", meaning:"รุนแรง, มาก" },
{ word:"십", meaning:"สิบ (10)" },
{ word:"십이월", meaning:"เดือนธันวาคม" },
{ word:"십일월", meaning:"เดือนพฤศจิกายน" },
{ word:"싱겁다", meaning:"ไม่เค็ม, จืด" },
{ word:"싶다", meaning:"อยาก" },
{ word:"싸다", meaning:"ถูก, ห่อ" },
{ word:"싸우다", meaning:"ทะเลาะ, ต่อสู้" },
{ word:"쌀", meaning:"ข้าวเปลือก" },
{ word:"쌀밥", meaning:"ข้าวสวย" },
{ word:"쌓이다", meaning:"กองสูงขึ้น, สะสม" },
{ word:"썰다", meaning:"หั่น, สับ" },
{ word:"쓰기", meaning:"การเขียน" },
{ word:"쓰다", meaning:"เขียน, ใช้, สวม (แว่นตา)" },
{ word:"쓰레기", meaning:"ขยะ" },
{ word:"쓰이다", meaning:"ถูกเขียน, ถูกใช้" },
{ word:"씨", meaning:"เมล็ด, คุณ~" },
{ word:"씩", meaning:"ละ, ต่อ, คนละ" },
{ word:"씹다", meaning:"เคี้ยว, กัด" },
{ word:"씻다", meaning:"ล้าง" },
{ word:"아가씨", meaning:"สาวน้อย, ลูกสาว" },
{ word:"아기", meaning:"ทารก, เด็กเล็ก" },
{ word:"아까", meaning:"เมื่อกี้, สักครู่ที่แล้ว" },
{ word:"아내", meaning:"ภรรยา" },
{ word:"아뇨", meaning:"ไม่" },
{ word:"아니다", meaning:"ไม่ใช่" },
{ word:"아니오", meaning:"ไม่" },
{ word:"아니요", meaning:"ไม่" },
{ word:"아들", meaning:"ลูกชาย" },
{ word:"아랍어", meaning:"ภาษาอาหรับ" },
{ word:"아래", meaning:"ข้างล่าง, ใต้" },
{ word:"아름답다", meaning:"สวยงาม" },
{ word:"아마", meaning:"บางที, อาจจะ" },
{ word:"아무", meaning:"ใดก็ได้, ทุก" },
{ word:"아버님", meaning:"พ่อ (แบบสุภาพ)" },
{ word:"아버지", meaning:"พ่อ" },
{ word:"아빠", meaning:"พ่อ (ภาษาพูด)" },
{ word:"아시아", meaning:"เอเชีย" },
{ word:"아이", meaning:"เด็ก" },
{ word:"아이스크림", meaning:"ไอศกรีม" },
{ word:"아저씨", meaning:"ลุง, คุณผู้ชาย" },
{ word:"아주", meaning:"มาก, อย่างสมบูรณ์" },
{ word:"아주머니", meaning:"ป้า, คุณผู้หญิง" },
{ word:"아줌마", meaning:"ป้า, คุณผู้หญิง" },
{ word:"아직", meaning:"ยัง, ยังคง" },
{ word:"아침", meaning:"เช้า, อาหารเช้า" },
{ word:"아침밥", meaning:"อาหารเช้า" },
{ word:"아침식사", meaning:"อาหารเช้า" },
{ word:"아파트", meaning:"อพาร์ตเมนต์" },
{ word:"아프다", meaning:"เจ็บปวด, ป่วย" },
{ word:"아프리카", meaning:"แอฟริกา" },
{ word:"아홉", meaning:"เก้า (9)" },
{ word:"아흔", meaning:"เก้าสิบ (90)" },
{ word:"악기", meaning:"เครื่องดนตรี" },
{ word:"안", meaning:"ข้างใน, ไม่~" },
{ word:"안경", meaning:"แว่นตา" },
{ word:"안내하다", meaning:"แนะนำ, นำทาง" },
{ word:"안녕하세요", meaning:"สวัสดี" },
{ word:"안녕하십니까", meaning:"สวัสดี (แบบสุภาพ)" },
{ word:"안다", meaning:"กอด, อุ้ม" },
{ word:"안전하다", meaning:"ปลอดภัย" },
{ word:"앉다", meaning:"นั่ง" },
{ word:"알다", meaning:"รู้, ทราบ" },
{ word:"알리다", meaning:"แจ้ง, บอก" },
{ word:"알맞다", meaning:"เหมาะสม, พอดี" },
{ word:"알았습니다", meaning:"เข้าใจแล้วครับ/ค่ะ" },
{ word:"앞", meaning:"ข้างหน้า, ก่อนหน้า" },
{ word:"애", meaning:"เด็ก" },
{ word:"액세서리", meaning:"เครื่องประดับ" },
{ word:"야구", meaning:"เบสบอล" },
{ word:"야채", meaning:"ผัก" },
{ word:"약", meaning:"ประมาณ, ยา" },
{ word:"약간", meaning:"เล็กน้อย" },
{ word:"약국", meaning:"ร้านขายยา" },
{ word:"약사", meaning:"เภสัชกร" },
{ word:"약속", meaning:"นัดหมาย, สัญญา" },
{ word:"얇다", meaning:"บาง" },
{ word:"양", meaning:"ปริมาณ, แกะ" },
{ word:"양말", meaning:"ถุงเท้า" },
{ word:"양복", meaning:"สูท" },
{ word:"양식", meaning:"แบบฟอร์ม, สไตล์ตะวันตก" },
{ word:"양파", meaning:"หัวหอม" },
{ word:"얘기하다", meaning:"คุย, พูดคุย" },
{ word:"어깨", meaning:"ไหล่" },
{ word:"어느", meaning:"ไหน, อย่างไร" },
{ word:"어둡다", meaning:"มืด" },
{ word:"어디", meaning:"ที่ไหน" },
{ word:"어떤", meaning:"อะไร, แบบไหน" },
{ word:"어떻게", meaning:"อย่างไร" },
{ word:"어떻다", meaning:"เป็นอย่างไร" },
{ word:"어떻습니까?", meaning:"เป็นอย่างไรบ้าง?" },
{ word:"어렵다", meaning:"ยาก" },
{ word:"어른", meaning:"ผู้ใหญ่" },
{ word:"어리다", meaning:"เด็ก, อายุน้อย" },
{ word:"어린이", meaning:"เด็ก" },
{ word:"어머", meaning:"โอ้, แหม" },
{ word:"어머니", meaning:"แม่" },
{ word:"어머님", meaning:"แม่ (แบบสุภาพ)" },
{ word:"어서", meaning:"เร็วๆ, ยินดีต้อนรับ" },
{ word:"어울리다", meaning:"เข้ากัน, เหมาะกับ" },
{ word:"어저께", meaning:"เมื่อวาน" },
{ word:"어제", meaning:"เมื่อวาน" },
{ word:"어젯밤", meaning:"คืนวานนี้" },
{ word:"언니", meaning:"พี่สาว (เรียกโดยน้องสาว)" },
{ word:"언제", meaning:"เมื่อไหร่" },
{ word:"언제나", meaning:"เสมอ, ตลอดเวลา" },
{ word:"얼굴", meaning:"ใบหน้า" },
{ word:"얼마나", meaning:"เท่าไหร่, มากแค่ไหน" },
{ word:"얼음", meaning:"น้ำแข็ง" },
{ word:"엄마", meaning:"แม่ (ภาษาพูด)" },
{ word:"없다", meaning:"ไม่มี" },
{ word:"없이", meaning:"โดยไม่มี, ปราศจาก" },
{ word:"에어컨", meaning:"เครื่องปรับอากาศ" },
{ word:"엔", meaning:"เยน" },
{ word:"엘리베이터", meaning:"ลิฟต์" },
{ word:"여권", meaning:"หนังสือเดินทาง" },
{ word:"여기", meaning:"ที่นี่" },
{ word:"여기저기", meaning:"ที่นี่ที่นั่น" },
{ word:"여덟", meaning:"แปด (8)" },
{ word:"여동생", meaning:"น้องสาว" },
{ word:"여든", meaning:"แปดสิบ (80)" },
{ word:"여러", meaning:"หลาย, มากมาย" },
{ word:"여러가지", meaning:"หลายอย่าง, หลากหลาย" },
{ word:"여러분", meaning:"ทุกคน, ท่านผู้ฟัง" },
{ word:"여름", meaning:"ฤดูร้อน" },
{ word:"여보세요", meaning:"ฮัลโหล (ทางโทรศัพท์)" },
{ word:"여섯", meaning:"หก (6)" },
{ word:"여자", meaning:"ผู้หญิง" },
{ word:"여학생", meaning:"นักเรียนหญิง" },
{ word:"여행", meaning:"การเดินทาง, ท่องเที่ยว" },
{ word:"여행사", meaning:"บริษัทท่องเที่ยว" },
{ word:"역", meaning:"สถานี" },
{ word:"역사", meaning:"ประวัติศาสตร์" },
{ word:"연락처", meaning:"ข้อมูลติดต่อ" },
{ word:"연세", meaning:"อายุ (แบบสุภาพ)" },
{ word:"연습", meaning:"การฝึกซ้อม" },
{ word:"연습하다", meaning:"ฝึกซ้อม" },
{ word:"연예인", meaning:"คนดัง, ดารา" },
{ word:"연필", meaning:"ดินสอ" },
{ word:"연휴", meaning:"วันหยุดต่อเนื่อง" },
{ word:"열", meaning:"สิบ (10)" },
{ word:"열다", meaning:"เปิด" },
{ word:"열리다", meaning:"ถูกเปิด" },
{ word:"열쇠", meaning:"กุญแจ" },
{ word:"열심히", meaning:"อย่างขยันขันแข็ง" },
{ word:"열차", meaning:"รถไฟ" },
{ word:"엽서", meaning:"โปสการ์ด" },
{ word:"영", meaning:"จิตวิญญาณ, ศูนย์" },
{ word:"영국", meaning:"สหราชอาณาจักร" },
{ word:"영상", meaning:"วิดีโอ" },
{ word:"영어", meaning:"ภาษาอังกฤษ" },
{ word:"영어회화", meaning:"การสนทนาภาษาอังกฤษ" },
{ word:"영하", meaning:"ติดลบ, ต่ำกว่าศูนย์" },
{ word:"영화", meaning:"ภาพยนตร์" },
{ word:"영화관", meaning:"โรงภาพยนตร์" },
{ word:"영화배우", meaning:"นักแสดงภาพยนตร์" },
{ word:"영화표", meaning:"ตั๋วภาพยนตร์" },
{ word:"옆", meaning:"ข้าง" },
{ word:"예", meaning:"ใช่, ครับ/ค่ะ" },
{ word:"예문", meaning:"ประโยคตัวอย่าง" },
{ word:"예쁘다", meaning:"สวย, น่ารัก" },
{ word:"예순", meaning:"หกสิบ (60)" },
{ word:"예약", meaning:"การจอง" },
{ word:"옛날", meaning:"นานมาแล้ว, สมัยก่อน" },
{ word:"오", meaning:"ห้า (5)" },
{ word:"오늘", meaning:"วันนี้" },
{ word:"오다", meaning:"มา" },
{ word:"오래", meaning:"นาน" },
{ word:"오래간만", meaning:"นานมาแล้ว" },
{ word:"오래간만입니다", meaning:"ไม่ได้เจอกันนานมาก" },
{ word:"오랜만", meaning:"นานมาแล้ว" },
{ word:"오랜만에", meaning:"หลังจากเวลานานมาก" },
{ word:"오랫동안", meaning:"เป็นเวลานาน" },
{ word:"오렌지", meaning:"ส้ม" },
{ word:"오르다", meaning:"ขึ้น, ปีน" },
{ word:"오른쪽", meaning:"ด้านขวา" },
{ word:"오리", meaning:"เป็ด" },
{ word:"오빠", meaning:"พี่ชาย (เรียกโดยน้องสาว)" },
{ word:"오십", meaning:"ห้าสิบ (50)" },
{ word:"오월", meaning:"เดือนพฤษภาคม" },
{ word:"오이", meaning:"แตงกวา" },
{ word:"오전", meaning:"ช่วงเช้า, ก่อนเที่ยง" },
{ word:"오징어", meaning:"ปลาหมึก" },
{ word:"오후", meaning:"ช่วงบ่าย, หลังเที่ยง" },
{ word:"올라가다", meaning:"ขึ้นไป" },
{ word:"올라오다", meaning:"ขึ้นมา" },
{ word:"올려놓다", meaning:"วางขึ้นบน" },
{ word:"올림픽", meaning:"โอลิมปิก" },
{ word:"올해", meaning:"ปีนี้" },
{ word:"옮기다", meaning:"ย้าย, โอน, แปล" },
{ word:"옷", meaning:"เสื้อผ้า" },
{ word:"옷가게", meaning:"ร้านเสื้อผ้า" },
{ word:"옷장", meaning:"ตู้เสื้อผ้า" },
{ word:"와이셔츠", meaning:"เสื้อเชิ้ต" },
{ word:"왜", meaning:"ทำไม" },
{ word:"왜냐하면", meaning:"เพราะว่า" },
{ word:"외국", meaning:"ต่างประเทศ" },
{ word:"외국어", meaning:"ภาษาต่างประเทศ" },
{ word:"외국인", meaning:"ชาวต่างชาติ" },
{ word:"외롭다", meaning:"โดดเดี่ยว, เหงา" },
{ word:"외삼촌", meaning:"ลุงฝ่ายแม่" },
{ word:"외숙모", meaning:"ป้าฝ่ายแม่" },
{ word:"외출하다", meaning:"ออกไปข้างนอก" },
{ word:"외할머니", meaning:"ยายฝ่ายแม่" },
{ word:"외할아버지", meaning:"ตาฝ่ายแม่" },
{ word:"왼쪽", meaning:"ด้านซ้าย" },
{ word:"요금", meaning:"ค่าธรรมเนียม" },
{ word:"요르단", meaning:"จอร์แดน" },
{ word:"요리", meaning:"การทำอาหาร, อาหาร" },
{ word:"요일", meaning:"วันในสัปดาห์" },
{ word:"요즘", meaning:"ช่วงนี้, เดี๋ยวนี้" },
{ word:"우리", meaning:"เรา, พวกเรา" },
{ word:"우리나라", meaning:"ประเทศของเรา, เกาหลีใต้" },
{ word:"우산", meaning:"ร่ม" },
{ word:"우선", meaning:"ก่อนอื่น" },
{ word:"우유", meaning:"นม" },
{ word:"우체국", meaning:"ไปรษณีย์" },
{ word:"우표", meaning:"แสตมป์" },
{ word:"운동", meaning:"การออกกำลังกาย" },
{ word:"운동복", meaning:"ชุดออกกำลังกาย" },
{ word:"운동선수", meaning:"นักกีฬา" },
{ word:"운동장", meaning:"สนามกีฬา, สนามเด็กเล่น" },
{ word:"운동하다", meaning:"ออกกำลังกาย" },
{ word:"운동화", meaning:"รองเท้ากีฬา" },
{ word:"운전하다", meaning:"ขับรถ" },
{ word:"울다", meaning:"ร้องไห้" },
{ word:"울리다", meaning:"ทำให้ร้องไห้, ดังกังวาน" },
{ word:"움직이다", meaning:"เคลื่อนไหว" },
{ word:"웃기다", meaning:"ตลก, ทำให้หัวเราะ" },
{ word:"웃다", meaning:"หัวเราะ" },
{ word:"원", meaning:"วอน (สกุลเงินเกาหลี)" },
{ word:"원피스", meaning:"ชุดเดรส" },
{ word:"원하다", meaning:"ต้องการ, ปรารถนา" },
{ word:"월", meaning:"เดือน" },
{ word:"월급", meaning:"เงินเดือน" },
{ word:"월드컵", meaning:"ฟุตบอลโลก" },
{ word:"월세", meaning:"ค่าเช่ารายเดือน" },
{ word:"월요일", meaning:"วันจันทร์" },
{ word:"웬일", meaning:"เรื่องอะไร, ด้วยเหตุใด" },
{ word:"위", meaning:"ข้างบน, บน" },
{ word:"위치", meaning:"ตำแหน่ง, ที่ตั้ง" },
{ word:"위하다", meaning:"เพื่อ, เพื่อประโยชน์ของ" },
{ word:"위험하다", meaning:"อันตราย" },
{ word:"유럽", meaning:"ยุโรป" },
{ word:"유리", meaning:"แก้ว" },
{ word:"유명하다", meaning:"มีชื่อเสียง" },
{ word:"유월", meaning:"เดือนมิถุนายน" },
{ word:"유학", meaning:"การเรียนต่อต่างประเทศ" },
{ word:"유학생", meaning:"นักเรียนต่างชาติ" },
{ word:"유행", meaning:"แฟชั่น, กระแสนิยม" },
{ word:"육", meaning:"หก (6)" },
{ word:"육십", meaning:"หกสิบ (60)" },
{ word:"은행", meaning:"ธนาคาร" },
{ word:"은행원", meaning:"พนักงานธนาคาร" },
{ word:"음료수", meaning:"เครื่องดื่ม" },
{ word:"음반", meaning:"แผ่นเสียง" },
{ word:"음식", meaning:"อาหาร" },
{ word:"음악", meaning:"ดนตรี" },
{ word:"음악가", meaning:"นักดนตรี" },
{ word:"응", meaning:"อืม, ใช่ (คำตอบ)" },
{ word:"의미", meaning:"ความหมาย" },
{ word:"의사", meaning:"แพทย์, หมอ" },
{ word:"의자", meaning:"เก้าอี้" },
{ word:"이", meaning:"นี้, ฟัน, สอง (2)" },
{ word:"이거", meaning:"นี่" },
{ word:"이것", meaning:"สิ่งนี้" },
{ word:"이곳", meaning:"ที่นี่" },
{ word:"이따가", meaning:"ภายหลัง, อีกครู่" },
{ word:"이런", meaning:"แบบนี้, อย่างนี้" },
{ word:"이렇게", meaning:"แบบนี้, อย่างนี้" },
{ word:"이렇다", meaning:"เป็นแบบนี้" },
{ word:"이름", meaning:"ชื่อ" },
{ word:"이메일", meaning:"อีเมล" },
{ word:"이모", meaning:"น้าสาว (ฝ่ายแม่)" },
{ word:"이모부", meaning:"น้าเขย (ฝ่ายแม่)" },
{ word:"이번", meaning:"ครั้งนี้" },
{ word:"이분", meaning:"คนนี้" },
{ word:"이사", meaning:"การย้ายบ้าน" },
{ word:"이상", meaning:"มากกว่า, แปลก" },
{ word:"이상하다", meaning:"แปลก, ประหลาด" },
{ word:"이십", meaning:"ยี่สิบ (20)" },
{ word:"이야기", meaning:"เรื่องราว" },
{ word:"이야기하다", meaning:"เล่าเรื่อง, คุย" },
{ word:"이용", meaning:"การใช้งาน" },
{ word:"이용하다", meaning:"ใช้งาน" },
{ word:"이월", meaning:"เดือนกุมภาพันธ์" },
{ word:"이유", meaning:"เหตุผล" },
{ word:"이제", meaning:"ตอนนี้, บัดนี้" },
{ word:"이집트", meaning:"อียิปต์" },
{ word:"이쪽", meaning:"ทางนี้, คนนี้" },
{ word:"이틀", meaning:"สองวัน" },
{ word:"이해", meaning:"ความเข้าใจ" },
{ word:"이해하다", meaning:"เข้าใจ" },
{ word:"인", meaning:"ลายเซ็น, ~คน" },
{ word:"인구", meaning:"ประชากร" },
{ word:"인기", meaning:"ความนิยม" },
{ word:"인기스타", meaning:"ดาราที่มีชื่อเสียง" },
{ word:"인도", meaning:"อินเดีย" },
{ word:"인사", meaning:"การทักทาย" },
{ word:"인사하다", meaning:"ทักทาย" },
{ word:"인삼", meaning:"โสม" },
{ word:"인상", meaning:"ความประทับใจ" },
{ word:"인천", meaning:"อินชอน" },
{ word:"인터넷", meaning:"อินเทอร์เน็ต" },
{ word:"인터뷰하다", meaning:"สัมภาษณ์" },
{ word:"인형", meaning:"ตุ๊กตา" },
{ word:"일", meaning:"งาน, หนึ่ง (1), วัน" },
{ word:"일곱", meaning:"เจ็ด (7)" },
{ word:"일기", meaning:"ไดอารี่" },
{ word:"일기예보", meaning:"พยากรณ์อากาศ" },
{ word:"일본", meaning:"ญี่ปุ่น" },
{ word:"일본드라마", meaning:"ละครญี่ปุ่น" },
{ word:"일본말", meaning:"ภาษาญี่ปุ่น" },
{ word:"일본사람", meaning:"คนญี่ปุ่น" },
{ word:"일본어", meaning:"ภาษาญี่ปุ่น" },
{ word:"일본요리", meaning:"อาหารญี่ปุ่น" },
{ word:"일상생활", meaning:"ชีวิตประจำวัน" },
{ word:"일식", meaning:"สไตล์ญี่ปุ่น, อาหารญี่ปุ่น" },
{ word:"일어나다", meaning:"ลุกขึ้น, เกิดขึ้น" },
{ word:"일어서다", meaning:"ลุกขึ้นยืน" },
{ word:"일요일", meaning:"วันอาทิตย์" },
{ word:"일월", meaning:"เดือนมกราคม" },
{ word:"일주일", meaning:"หนึ่งสัปดาห์" },
{ word:"일찍", meaning:"แต่เนิ่นๆ, เร็ว" },
{ word:"일하다", meaning:"ทำงาน" },
{ word:"일흔", meaning:"เจ็ดสิบ (70)" },
{ word:"읽기", meaning:"การอ่าน" },
{ word:"읽다", meaning:"อ่าน" },
{ word:"잃다", meaning:"สูญเสีย" },
{ word:"잃어버리다", meaning:"ทำหาย" },
{ word:"입", meaning:"ปาก" },
{ word:"입구", meaning:"ทางเข้า" },
{ word:"입다", meaning:"ใส่, สวมใส่ (เสื้อผ้า)" },
{ word:"입원하다", meaning:"เข้าโรงพยาบาล" },
{ word:"입학", meaning:"การเข้าเรียน" },
{ word:"있다", meaning:"มี, อยู่" },
{ word:"잊다", meaning:"ลืม" },
{ word:"잊어버리다", meaning:"ลืมสนิท" },
{ word:"자", meaning:"ตัวอักษร, มาเลย" },
{ word:"자기", meaning:"ตัวเอง" },
{ word:"자다", meaning:"นอนหลับ" },
{ word:"자동차", meaning:"รถยนต์" },
{ word:"자동차회사", meaning:"บริษัทรถยนต์" },
{ word:"자료", meaning:"เอกสาร, ข้อมูล" },
{ word:"자르다", meaning:"ตัด" },
{ word:"자리", meaning:"ที่นั่ง, ตำแหน่ง" },
{ word:"자신", meaning:"ตัวเอง" },
{ word:"자연", meaning:"ธรรมชาติ" },
{ word:"자유", meaning:"เสรีภาพ" },
{ word:"자장면", meaning:"จาจังมยอน (บะหมี่ซอสดำ)" },
{ word:"자전거", meaning:"จักรยาน" },
{ word:"자주", meaning:"บ่อยๆ" },
{ word:"작년", meaning:"ปีที่แล้ว" },
{ word:"작다", meaning:"เล็ก" },
{ word:"작은아버지", meaning:"อา (น้องชายของพ่อ)" },
{ word:"작은어머니", meaning:"อา (ภรรยาของน้องชายพ่อ)" },
{ word:"잔", meaning:"แก้ว, ~แก้ว" },
{ word:"잔치", meaning:"งานเลี้ยง, งานฉลอง" },
{ word:"잘", meaning:"ดี, เก่ง" },
{ word:"잘못", meaning:"ความผิดพลาด" },
{ word:"잘생기다", meaning:"หล่อ" },
{ word:"잘하다", meaning:"ทำได้ดี, เก่ง" },
{ word:"잠", meaning:"การนอนหลับ" },
{ word:"잠깐", meaning:"สักครู่" },
{ word:"잠시", meaning:"ชั่วขณะ, สักครู่" },
{ word:"잠자다", meaning:"นอนหลับ" },
{ word:"잡다", meaning:"จับ, คว้า" },
{ word:"잡수시다", meaning:"รับประทาน (แบบสุภาพ)" },
{ word:"잡지", meaning:"นิตยสาร" },
{ word:"장", meaning:"~บท, ~แผ่น" },
{ word:"장갑", meaning:"ถุงมือ" },
{ word:"장마", meaning:"ฤดูฝน" },
{ word:"장마철", meaning:"ช่วงฤดูฝน" },
{ word:"장미", meaning:"ดอกกุหลาบ" },
{ word:"장소", meaning:"สถานที่" },
{ word:"장점", meaning:"ข้อดี, จุดเด่น" },
{ word:"재료", meaning:"วัตถุดิบ, ส่วนผสม" },
{ word:"재미없다", meaning:"ไม่สนุก, น่าเบื่อ" },
{ word:"재미있다", meaning:"สนุก, น่าสนใจ" },
{ word:"재킷", meaning:"แจ็กเก็ต" },
{ word:"저", meaning:"นั่น" },
{ word:"저거", meaning:"นั่น" },
{ word:"저것", meaning:"สิ่งนั้น" },
{ word:"저곳", meaning:"ที่นั่น, โน่น" },
{ word:"저기", meaning:"ที่นั่น, โน่น" },
{ word:"저녁", meaning:"อาหารเย็น, ตอนเย็น" },
{ word:"저녁식사", meaning:"มื้อเย็น" },
{ word:"저렇게", meaning:"แบบนั้น, อย่างนั้น" },
{ word:"저분", meaning:"คนนั้น" },
{ word:"저쪽", meaning:"ทางนั้น, โน่น" },
{ word:"저희", meaning:"พวกเรา (แบบถ่อมตน)" },
{ word:"적", meaning:"ศัตรู" },
{ word:"적다", meaning:"น้อย, จดบันทึก" },
{ word:"전", meaning:"ทั้งหมด, ก่อน" },
{ word:"전공", meaning:"วิชาเอก" },
{ word:"전기자동차", meaning:"รถยนต์ไฟฟ้า" },
{ word:"전자사전", meaning:"พจนานุกรมอิเล็กทรอนิกส์" },
{ word:"전하다", meaning:"บอก, ส่งต่อ" },
{ word:"전혀", meaning:"ไม่เลย, เลยทีเดียว" },
{ word:"전화", meaning:"โทรศัพท์" },
{ word:"전화기", meaning:"เครื่องโทรศัพท์" },
{ word:"전화번호", meaning:"หมายเลขโทรศัพท์" },
{ word:"절", meaning:"~ส่วน, วัด" },
{ word:"절대", meaning:"ไม่มีทาง, เด็ดขาด" },
{ word:"젊다", meaning:"หนุ่มสาว, อายุน้อย" },
{ word:"점", meaning:"คะแนน, จุด" },
{ word:"점수", meaning:"คะแนน" },
{ word:"점심", meaning:"อาหารกลางวัน" },
{ word:"점심시간", meaning:"เวลาพักกลางวัน" },
{ word:"점심식사", meaning:"มื้อกลางวัน" },
{ word:"점원", meaning:"พนักงานขาย" },
{ word:"점퍼", meaning:"แจ็กเก็ต" },
{ word:"젓가락", meaning:"ตะเกียบ" },
{ word:"정거장", meaning:"สถานี, ป้ายรถ" },
{ word:"정도", meaning:"ระดับ, ประมาณ" },
{ word:"정류장", meaning:"ป้ายรถเมล์, สถานี" },
{ word:"정리하다", meaning:"จัดระเบียบ, เก็บของ" },
{ word:"정말", meaning:"จริงๆ" },
{ word:"정문", meaning:"ประตูหน้า, ทางเข้าหลัก" },
{ word:"정보", meaning:"ข้อมูล" },
{ word:"정하다", meaning:"กำหนด, ตัดสินใจ" },
{ word:"제가", meaning:"ผม/หนู (แบบสุภาพ)" },
{ word:"제목", meaning:"ชื่อเรื่อง, หัวข้อ" },
{ word:"제일", meaning:"ที่สุด, อันดับหนึ่ง" },
{ word:"제주도", meaning:"เกาะเชจู" },
{ word:"조금", meaning:"นิดหน่อย" },
{ word:"조사하다", meaning:"สืบสวน, ตรวจสอบ" },
{ word:"조선", meaning:"การต่อเรือ, โชซอน" },
{ word:"조선말", meaning:"ภาษาเกาหลี" },
{ word:"조선어", meaning:"ภาษาเกาหลี" },
{ word:"조심하다", meaning:"ระวัง, ระมัดระวัง" },
{ word:"조용하다", meaning:"เงียบ, สงบ" },
{ word:"조용히", meaning:"อย่างเงียบๆ" },
{ word:"조카", meaning:"หลานชาย/หลานสาว" },
{ word:"졸업", meaning:"การสำเร็จการศึกษา" },
{ word:"졸업하다", meaning:"สำเร็จการศึกษา" },
{ word:"좀", meaning:"นิดหน่อย, ช่วย~หน่อย" },
{ word:"좀더", meaning:"อีกนิดหน่อย" },
{ word:"좁다", meaning:"แคบ" },
{ word:"종로", meaning:"จงโร" },
{ word:"종류", meaning:"ประเภท, ชนิด" },
{ word:"종업원", meaning:"พนักงาน" },
{ word:"종이", meaning:"กระดาษ" },
{ word:"종일", meaning:"ตลอดวัน" },
{ word:"좋다", meaning:"ดี" },
{ word:"좋아하다", meaning:"ชอบ" },
{ word:"죄송하다", meaning:"ขอโทษ (แบบสุภาพ)" },
{ word:"주", meaning:"สัปดาห์" },
{ word:"주다", meaning:"ให้" },
{ word:"주로", meaning:"ส่วนใหญ่" },
{ word:"주말", meaning:"วันหยุดสุดสัปดาห์" },
{ word:"주머니", meaning:"กระเป๋า, ถุง" },
{ word:"주무시다", meaning:"นอนหลับ (แบบสุภาพ)" },
{ word:"주문하다", meaning:"สั่ง (อาหาร/สินค้า)" },
{ word:"주변", meaning:"บริเวณรอบๆ" },
{ word:"주부", meaning:"แม่บ้าน" },
{ word:"주사", meaning:"การฉีดยา" },
{ word:"주소", meaning:"ที่อยู่" },
{ word:"주스", meaning:"น้ำผลไม้" },
{ word:"주위", meaning:"รอบๆ" },
{ word:"주인", meaning:"เจ้าของ" },
{ word:"주차장", meaning:"ที่จอดรถ" },
{ word:"주차하다", meaning:"จอดรถ" },
{ word:"주황색", meaning:"สีส้ม" },
{ word:"죽", meaning:"ไม้ไผ่, โจ๊ก" },
{ word:"죽다", meaning:"ตาย" },
{ word:"준비", meaning:"การเตรียม" },
{ word:"준비하다", meaning:"เตรียม" },
{ word:"줄", meaning:"เส้น, แถว, เชือก" },
{ word:"줄다", meaning:"ลด, หด" },
{ word:"중", meaning:"ขนาดกลาง, ระหว่าง" },
{ word:"중국", meaning:"จีน" },
{ word:"중국어", meaning:"ภาษาจีน" },
{ word:"중국집", meaning:"ร้านอาหารจีน" },
{ word:"중식", meaning:"อาหารจีน" },
{ word:"중심", meaning:"ศูนย์กลาง" },
{ word:"중요", meaning:"ความสำคัญ" },
{ word:"중요하다", meaning:"สำคัญ" },
{ word:"중학교", meaning:"โรงเรียนมัธยมต้น" },
{ word:"중학생", meaning:"นักเรียนมัธยมต้น" },
{ word:"즐거워하다", meaning:"สนุกสนาน" },
{ word:"즐겁다", meaning:"สนุก, มีความสุข" },
{ word:"즐기다", meaning:"เพลิดเพลิน, สนุกกับ" },
{ word:"증세", meaning:"อาการ, อาการป่วย" },
{ word:"지각", meaning:"การมาสาย" },
{ word:"지갑", meaning:"กระเป๋าสตางค์" },
{ word:"지금", meaning:"ตอนนี้" },
{ word:"지나다", meaning:"ผ่านไป" },
{ word:"지난달", meaning:"เดือนที่แล้ว" },
{ word:"지난번", meaning:"ครั้งที่แล้ว" },
{ word:"지난주", meaning:"สัปดาห์ที่แล้ว" },
{ word:"지내다", meaning:"อยู่, ใช้ชีวิต" },
{ word:"지다", meaning:"แพ้" },
{ word:"지도", meaning:"แผนที่" },
{ word:"지방", meaning:"ไขมัน, ภูมิภาค" },
{ word:"지우개", meaning:"ยางลบ" },
{ word:"지키다", meaning:"ปกป้อง, รักษา" },
{ word:"지하", meaning:"ใต้ดิน" },
{ word:"지하도", meaning:"ทางลอดใต้ดิน" },
{ word:"지하철", meaning:"รถไฟฟ้าใต้ดิน" },
{ word:"지하철역", meaning:"สถานีรถไฟฟ้าใต้ดิน" },
{ word:"직업", meaning:"อาชีพ" },
{ word:"직원", meaning:"พนักงาน, เจ้าหน้าที่" },
{ word:"직장", meaning:"ที่ทำงาน" },
{ word:"직접", meaning:"โดยตรง" },
{ word:"진달래", meaning:"ดอกอะซาเลีย" },
{ word:"질", meaning:"คุณภาพ" },
{ word:"질문", meaning:"คำถาม" },
{ word:"질문하다", meaning:"ถามคำถาม" },
{ word:"짐", meaning:"สัมภาระ, ของ" },
{ word:"집", meaning:"บ้าน, ร้าน" },
{ word:"짓다", meaning:"สร้าง, ทำ" },
{ word:"짜다", meaning:"เค็ม, วางแผน" },
{ word:"짜리", meaning:"มูลค่า (สกุลเงิน)" },
{ word:"짧다", meaning:"สั้น" },
{ word:"쪽", meaning:"ด้าน, หน้า" },
{ word:"쯤", meaning:"ประมาณ, ราวๆ" },
{ word:"찌개", meaning:"ซุปข้น, สตูว์" },
{ word:"찍다", meaning:"เจาะ, ถ่ายรูป, กด" },
{ word:"차", meaning:"รถ, ชา" },
{ word:"차갑다", meaning:"เย็น" },
{ word:"차다", meaning:"เตะ" },
{ word:"차리다", meaning:"เตรียม, จัดเตรียม" },
{ word:"착하다", meaning:"ใจดี, เป็นคนดี" },
{ word:"참", meaning:"จริงๆ, มาก" },
{ word:"창문", meaning:"หน้าต่าง" },
{ word:"찾다", meaning:"หา, เยี่ยม" },
{ word:"찾아가다", meaning:"ไปเยี่ยม" },
{ word:"찾아오다", meaning:"มาเยี่ยม" },
{ word:"채소", meaning:"ผัก" },
{ word:"책", meaning:"หนังสือ" },
{ word:"책방", meaning:"ร้านหนังสือ" },
{ word:"책상", meaning:"โต๊ะทำงาน" },
{ word:"책임", meaning:"ความรับผิดชอบ" },
{ word:"책장", meaning:"ชั้นวางหนังสือ" },
{ word:"처음", meaning:"ครั้งแรก, เป็นครั้งแรก" },
{ word:"처음 뵙겠습니다", meaning:"ยินดีที่ได้รู้จัก" },
{ word:"천", meaning:"หนึ่งพัน (1000)" },
{ word:"천천히", meaning:"ช้าๆ" },
{ word:"철", meaning:"เหล็ก, ฤดู" },
{ word:"첫", meaning:"แรก, ที่หนึ่ง" },
{ word:"첫째", meaning:"อันดับแรก" },
{ word:"청바지", meaning:"กางเกงยีนส์" },
{ word:"청소기", meaning:"เครื่องดูดฝุ่น" },
{ word:"청소하다", meaning:"ทำความสะอาด" },
{ word:"초", meaning:"~วินาที" },
{ word:"초대하다", meaning:"เชิญ" },
{ word:"초등학교", meaning:"โรงเรียนประถม" },
{ word:"초등학생", meaning:"นักเรียนประถม" },
{ word:"초록색", meaning:"สีเขียว" },
{ word:"초콜릿", meaning:"ช็อกโกแลต" },
{ word:"촬영하다", meaning:"ถ่ายรูป, ถ่ายทำ" },
{ word:"최고", meaning:"ดีที่สุด, สูงสุด" },
{ word:"추다", meaning:"เต้นรำ" },
{ word:"추석", meaning:"วันขอบคุณพระเจ้าของเกาหลี" },
{ word:"추억", meaning:"ความทรงจำ" },
{ word:"축구", meaning:"ฟุตบอล" },
{ word:"축제", meaning:"เทศกาล" },
{ word:"축하", meaning:"การ祝祝ฉลอง" },
{ word:"축하하다", meaning:"ฉลอง, แสดงความยินดี" },
{ word:"축하합니다", meaning:"ยินดีด้วย" },
{ word:"출구", meaning:"ทางออก" },
{ word:"출근하다", meaning:"ไปทำงาน" },
{ word:"출발", meaning:"การออกเดินทาง" },
{ word:"출발하다", meaning:"ออกเดินทาง" },
{ word:"출장", meaning:"การเดินทางเพื่อธุรกิจ" },
{ word:"춤", meaning:"การเต้นรำ" },
{ word:"춤추다", meaning:"เต้นรำ" },
{ word:"춥다", meaning:"หนาว" },
{ word:"취미", meaning:"งานอดิเรก" },
{ word:"취소하다", meaning:"ยกเลิก" },
{ word:"취직하다", meaning:"ได้งานทำ" },
{ word:"층", meaning:"ชั้น" },
{ word:"치과", meaning:"ทันตกรรม, คลินิกฟัน" },
{ word:"치료하다", meaning:"รักษา" },
{ word:"치마", meaning:"กระโปรง" },
{ word:"치약", meaning:"ยาสีฟัน" },
{ word:"친구", meaning:"เพื่อน" },
{ word:"친절하다", meaning:"ใจดี, เป็นมิตร" },
{ word:"친척", meaning:"ญาติ" },
{ word:"친하다", meaning:"สนิท, คุ้นเคย" },
{ word:"칠", meaning:"เจ็ด (7)" },
{ word:"칠십", meaning:"เจ็ดสิบ (70)" },
{ word:"칠월", meaning:"เดือนกรกฎาคม" },
{ word:"칠판", meaning:"กระดานดำ" },
{ word:"침대", meaning:"เตียง" },
{ word:"칫솔", meaning:"แปรงสีฟัน" },
{ word:"카드", meaning:"การ์ด" },
{ word:"카레", meaning:"แกงกะหรี่" },
{ word:"카메라", meaning:"กล้องถ่ายรูป" },
{ word:"카페", meaning:"คาเฟ่, ร้านกาแฟ" },
{ word:"칼", meaning:"มีด" },
{ word:"캐나다", meaning:"แคนาดา" },
{ word:"커피", meaning:"กาแฟ" },
{ word:"커피숍", meaning:"ร้านกาแฟ" },
{ word:"컴퓨터", meaning:"คอมพิวเตอร์" },
{ word:"컵", meaning:"ถ้วย, แก้ว" },
{ word:"케이크", meaning:"เค้ก" },
{ word:"켜다", meaning:"เปิด (ไฟ, สวิตช์)" },
{ word:"코", meaning:"จมูก" },
{ word:"코트", meaning:"เสื้อโค้ท" },
{ word:"코피", meaning:"เลือดกำเดา" },
{ word:"콜라", meaning:"โค้ก" },
{ word:"콧노래", meaning:"การฮัมเพลง" },
{ word:"콧물", meaning:"น้ำมูก" },
{ word:"콩", meaning:"ถั่ว" },
{ word:"크기", meaning:"ขนาด" },
{ word:"크다", meaning:"ใหญ่, โต" },
{ word:"크리스마스", meaning:"คริสต์มาส" },
{ word:"큰아버지", meaning:"ลุง (พี่ชายของพ่อ)" },
{ word:"큰어머니", meaning:"ป้า (ภรรยาพี่ชายของพ่อ)" },
{ word:"키", meaning:"กุญแจ, ส่วนสูง" },
{ word:"킬로그램", meaning:"กิโลกรัม" },
{ word:"킬로미터", meaning:"กิโลเมตร" },
{ word:"타다", meaning:"ขึ้น, โดยสาร" },
{ word:"타월", meaning:"ผ้าเช็ดตัว" },
{ word:"탁구", meaning:"ปิงปอง" },
{ word:"태국", meaning:"ประเทศไทย" },
{ word:"태권도", meaning:"เทควันโด" },
{ word:"태어나다", meaning:"เกิด" },
{ word:"태풍", meaning:"ไต้ฝุ่น" },
{ word:"택시", meaning:"แท็กซี่" },
{ word:"탤런트", meaning:"นักแสดง, ดารา" },
{ word:"터미널", meaning:"เทอร์มินัล, สถานีขนส่ง" },
{ word:"테니스", meaning:"เทนนิส" },
{ word:"테이블", meaning:"โต๊ะ" },
{ word:"텔레비전", meaning:"โทรทัศน์" },
{ word:"토마토", meaning:"มะเขือเทศ" },
{ word:"토요일", meaning:"วันเสาร์" },
{ word:"통", meaning:"ถัง, ~ห่อ" },
{ word:"통장", meaning:"สมุดบัญชีธนาคาร" },
{ word:"통하다", meaning:"ผ่าน, นำไปสู่" },
{ word:"퇴근하다", meaning:"เลิกงาน" },
{ word:"특별히", meaning:"โดยเฉพาะ" },
{ word:"특징", meaning:"ลักษณะเฉพาะ, คุณสมบัติ" },
{ word:"특히", meaning:"โดยเฉพาะ, โดยเฉพาะอย่างยิ่ง" },
{ word:"틀다", meaning:"เปิด (สวิตช์)" },
{ word:"틀리다", meaning:"ผิด" },
{ word:"티셔츠", meaning:"เสื้อยืด" },
{ word:"팀", meaning:"ทีม" },
{ word:"파", meaning:"คลื่น, ต้นหอม" },
{ word:"파란색", meaning:"สีน้ำเงิน" },
{ word:"파랗다", meaning:"น้ำเงิน" },
{ word:"파티", meaning:"ปาร์ตี้" },
{ word:"팔", meaning:"แปด (8)" },
{ word:"팔다", meaning:"ขาย" },
{ word:"팔리다", meaning:"ถูกขาย" },
{ word:"팔십", meaning:"แปดสิบ (80)" },
{ word:"팔월", meaning:"เดือนสิงหาคม" },
{ word:"패션", meaning:"แฟชั่น" },
{ word:"퍼센트", meaning:"เปอร์เซ็นต์" },
{ word:"페이지", meaning:"หน้า" },
{ word:"펜", meaning:"ปากกา" },
{ word:"펴다", meaning:"펼치다, ยืด" },
{ word:"편", meaning:"ด้าน, ตอน" },
{ word:"편지", meaning:"จดหมาย" },
{ word:"편하다", meaning:"สะดวกสบาย" },
{ word:"평양", meaning:"เปียงยาง" },
{ word:"평일", meaning:"วันธรรมดา" },
{ word:"포도", meaning:"องุ่น" },
{ word:"포장", meaning:"การบรรจุหีบห่อ" },
{ word:"표", meaning:"ตาราง, ตั๋ว" },
{ word:"표현", meaning:"การแสดงออก" },
{ word:"푹", meaning:"อย่างลึก, อย่างเต็มที่" },
{ word:"풀", meaning:"สระ, หญ้า" },
{ word:"풀다", meaning:"แก้, คลาย" },
{ word:"프랑스", meaning:"ฝรั่งเศส" },
{ word:"프로그램", meaning:"โปรแกรม" },
{ word:"프린트", meaning:"พิมพ์" },
{ word:"피", meaning:"เลือด" },
{ word:"피곤하다", meaning:"เหนื่อย, อ่อนล้า" },
{ word:"피다", meaning:"บาน, ผลิ" },
{ word:"피아노", meaning:"เปียโน" },
{ word:"피우다", meaning:"สูบ, ทำให้บาน" },
{ word:"피자", meaning:"พิซซ่า" },
{ word:"필름", meaning:"ฟิล์ม" },
{ word:"필요", meaning:"ความจำเป็น" },
{ word:"필요하다", meaning:"จำเป็น, ต้องการ" },
{ word:"필통", meaning:"กล่องดินสอ" },
{ word:"하나", meaning:"หนึ่ง (1)" },
{ word:"하늘", meaning:"ท้องฟ้า" },
{ word:"하늘색", meaning:"สีฟ้า, สีท้องฟ้า" },
{ word:"하다", meaning:"ทำ, พูด" },
{ word:"하루", meaning:"หนึ่งวัน" },
{ word:"하숙", meaning:"หอพัก" },
{ word:"하숙집", meaning:"บ้านพัก, หอพัก" },
{ word:"하얀색", meaning:"สีขาว" },
{ word:"하얗다", meaning:"ขาว" },
{ word:"하지만", meaning:"แต่, อย่างไรก็ตาม" },
{ word:"학", meaning:"นกกระเรียน" },
{ word:"학교", meaning:"โรงเรียน" },
{ word:"학기", meaning:"ภาคการศึกษา" },
{ word:"학년", meaning:"ชั้นปี, ปีการศึกษา" },
{ word:"학생", meaning:"นักเรียน, นักศึกษา" },
{ word:"학생증", meaning:"บัตรนักเรียน" },
{ word:"학원", meaning:"โรงเรียนกวดวิชา" },
{ word:"한", meaning:"หนึ่ง, หนึ่งใน~" },
{ word:"한강", meaning:"แม่น้ำฮัน" },
{ word:"한국", meaning:"เกาหลี" },
{ word:"한국드라마", meaning:"ละครเกาหลี" },
{ word:"한국말", meaning:"ภาษาเกาหลี" },
{ word:"한국사람", meaning:"คนเกาหลี" },
{ word:"한국어", meaning:"ภาษาเกาหลี" },
{ word:"한국요리", meaning:"อาหารเกาหลี" },
{ word:"한글", meaning:"ฮันกึล (อักษรเกาหลี)" },
{ word:"한번", meaning:"ครั้งหนึ่ง, ลองดู" },
{ word:"한복", meaning:"ฮันบก (ชุดประจำชาติเกาหลี)" },
{ word:"한식", meaning:"อาหารเกาหลี" },
{ word:"한자", meaning:"อักษรจีน" },
{ word:"할머니", meaning:"คุณย่า, คุณยาย" },
{ word:"할아버지", meaning:"คุณปู่, คุณตา" },
{ word:"할인", meaning:"ส่วนลด" },
{ word:"함께", meaning:"ด้วยกัน, พร้อมกัน" },
{ word:"합격", meaning:"การสอบผ่าน" },
{ word:"항상", meaning:"เสมอ, ตลอดเวลา" },
{ word:"해", meaning:"ปี, ดวงอาทิตย์" },
{ word:"해외", meaning:"ต่างประเทศ" },
{ word:"해외여행", meaning:"การเดินทางต่างประเทศ" },
{ word:"핸드폰", meaning:"โทรศัพท์มือถือ" },
{ word:"햄버거", meaning:"แฮมเบอร์เกอร์" },
{ word:"햇빛", meaning:"แสงแดด" },
{ word:"행복", meaning:"ความสุข" },
{ word:"행복하다", meaning:"มีความสุข" },
{ word:"행사", meaning:"งาน, กิจกรรม" },
{ word:"허리", meaning:"เอว, สะโพก" },
{ word:"현금", meaning:"เงินสด" },
{ word:"현재", meaning:"ปัจจุบัน" },
{ word:"형", meaning:"พี่ชาย (เรียกโดยน้องชาย)" },
{ word:"형님", meaning:"พี่ชาย (แบบสุภาพ)" },
{ word:"형제", meaning:"พี่น้อง" },
{ word:"호", meaning:"ฉบับที่~, หมายเลข~" },
{ word:"호랑이", meaning:"เสือ" },
{ word:"호주", meaning:"ออสเตรเลีย" },
{ word:"호텔", meaning:"โรงแรม" },
{ word:"혼자", meaning:"คนเดียว" },
{ word:"홈페이지", meaning:"โฮมเพจ, เว็บไซต์" },
{ word:"홍차", meaning:"ชาดำ" },
{ word:"화", meaning:"ความโกรธ" },
{ word:"화가", meaning:"จิตรกร, ศิลปิน" },
{ word:"화나다", meaning:"โกรธ" },
{ word:"화내다", meaning:"แสดงความโกรธ" },
{ word:"화요일", meaning:"วันอังคาร" },
{ word:"화장실", meaning:"ห้องน้ำ" },
{ word:"화장품", meaning:"เครื่องสำอาง" },
{ word:"화장하다", meaning:"แต่งหน้า" },
{ word:"확인하다", meaning:"ยืนยัน, ตรวจสอบ" },
{ word:"환영하다", meaning:"ต้อนรับ" },
{ word:"환자", meaning:"ผู้ป่วย" },
{ word:"회사", meaning:"บริษัท" },
{ word:"회사원", meaning:"พนักงานบริษัท" },
{ word:"회색", meaning:"สีเทา" },
{ word:"회의", meaning:"การประชุม" },
{ word:"횡단보도", meaning:"ทางม้าลาย" },
{ word:"후", meaning:"หลังจาก" },
{ word:"후배", meaning:"รุ่นน้อง" },
{ word:"휴가", meaning:"วันหยุด, การลาพัก" },
{ word:"휴대전화", meaning:"โทรศัพท์มือถือ" },
{ word:"휴일", meaning:"วันหยุด" },
{ word:"휴지", meaning:"กระดาษทิชชู่" },
{ word:"휴지통", meaning:"ถังขยะ" },
{ word:"흐리다", meaning:"มีเมฆมาก, ขุ่นมัว" },
{ word:"흰색", meaning:"สีขาว" },
{ word:"힘", meaning:"พลัง, แรง" }
];